### ISSUE TITLE
Lacking documentation

### ISSUE THREAD

**Issue by Bob-Dzimbowski** [MicrosoftDocs/dynamics365smb-docs#106]
I find all the documentation in general to be lacking and difficult to learn because it does not precisely follow the software and there are NO screen shots to clarify things. OMG! So I am trying to learn about config packages and it is taking forever. There is no documentation that explains what all the controls on the various screens are for and I am having a hell of a time trying to get it to work because I don't understand half the things on the screen because there is no reference guide. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c17285d-1100-c2f7-aa54-588c98bd6834
* Version Independent ID: 823c90f0-592f-7d40-6c97-1ac7b7adcf13
* Content: [How to Prepare a Configuration Package - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/admin-how-to-prepare-a-configuration-package#see-also)
* Content Source: [business-central/admin-how-to-prepare-a-configuration-package.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-to-prepare-a-configuration-package.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hello - Sorry to hear about your frustration. Below are some explanations that may not help you, but unfortunately is all I can offer you. 

- For reasons pertaining to the translation process, we deliberately do not have screen shots in Business Central help.
- Help for individual fields and actions in the UI are provided with tooltips only. Hover over a field to read a short description.
- RapidStart Services is a fairly complicated toolset, which is designed for solution implementers. Documentation is therefore not to the same detail level as end-user functionality.

TIP: For training and videos on this toolset, search online for "RapidStart + Dynamics NAV".  

PS: The Canada version of this help topic is slightly behind the US version (because of the translation roll-out process). To see the latest content, with a better table of contents, for example, change the language at the bottom of the Docs site to English (United States).

Regards
Soren, Business Central writer
