### ISSUE TITLE
Doesn't fully cover how to handle Credit Card Payments

### ISSUE THREAD

**Issue by JohnGalt1717** [MicrosoftDocs/dynamics365smb-docs#109]
Here's the scenario that most customers will face:

1. Invoice is generated.
2. Payment is taken against a credit card.
3. Funds are not deposited immediately, instead they typically are stored in "undeposited funds"
4. Credit Card Processing company completes the transaction by depositing funds into your bank account in a lump sum.
5. Visa and MasterCard do this by doing a lump sum payment of the total of all transactions for period. Amex does this as lump sum payment of total of all transactions less their fees.
6. Customer needs to link the undeposited funds to the actual lump sum and do an entry from undeposited funds to the bank account (and in the case of Amex their CC cost account on a/p).

I can find no documentation anywhere on how this should be done and it isn't clear from this documentation if this is how or there is another process. If this is how, then it needs to be made far more clear. If this isn't how, then a new item in this section needs to be created that fully describes this process of recording CC payments without funds and then receiving funds and reconciling.  Hopefully this is just incomplete documentation and not a major missing function of the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b825e6d-f005-b0a4-c2a4-57bf9ea3a483
* Version Independent ID: 1607ed34-6562-bbf4-dd4b-d76533a6f99a
* Content: [Use Automatic Application to Reconcile Payments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/receivables-how-reconcile-payments-auto-application)
* Content Source: [business-central/receivables-how-reconcile-payments-auto-application.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/receivables-how-reconcile-payments-auto-application.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hi - Thank you for the feedback

In Help for payment processing, we deliberately do not specifically describe a credit-card process or that of any other payment means. Instead, we refer generically to "payments" and to the resulting bank transactions. This because payment means vary geographically and change over time, but also because the nature of Business Central is to be an application platform, not a customer solution.

Accordingly, the standard version of  Business Central does not have dedicated functionality for the credit card scenario that you describe, however the scenario is most likely supported with a comparable method using the standard functionality. See for example this topic about handling lump-sum customer payments: https://docs.microsoft.com/en-us/dynamics365/business-central/receivables-how-reconcile-customer-payments-list-unpaid-sales-documents#to-reconcile-lump-payments. Also, the Deposits feature in the standard US version may be relevant for you. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedstates/how-to-create-deposits. 

If you need dedicated credit card functionality in Business Central, try to search for a relevant extension on AppSource: https://appsource.microsoft.com/en-us/marketplace/apps?product=dynamics-365-business-central.

Regards
Soren, Business Central writer
