### ISSUE TITLE
Page location/breadcrumb

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/dynamics365smb-docs#125]
The breadcrumb displays a location that does not correspond to the location in the TOC.

In some cases, this behavior is by design: when the page exists in multiple locations,
the breadcrumb displays only one location, and it might not correspond to the location that is currently displayed in TOC.

But in this case, it seems to be an issue:
if you use the TOC to browse to the location indicated by the breadcrumb
(Setting Up Business Central / Complex Application Areas / Global Planning Setup / Reordering Policies)
clicking the entry "Setup Best Practices: Reordering Policies" opens the "Managing Saved Settings on Reports" page, which is irrelevant.
The real "Reordering Policies" page is here:
https://docs.microsoft.com/en-us/dynamics365/business-central/setup-best-practices-reordering-policies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d4fb346-0ffe-7f89-9ca6-56ce1a92b82f
* Version Independent ID: 822a9737-5a78-1d0c-ef1e-2098f54acb7e
* Content: [Apply and Modify Saved Settings on Reports - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/reports-saving-reusing-settings)
* Content Source: [business-central/reports-saving-reusing-settings.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/reports-saving-reusing-settings.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hi a-zaf,

Thank you for your feedback! The breadcrumbs and the table of contents are designed to supplement each other. The breadcrumbs are generated based on the table of contents plus a basic setup based on folder structure.
In your concrete example, there are two entries in the table of contents for the Setup Best Practices: Reordering Policies article, and one of them does indeed go to the wrong location. Our team will get this fixed in the next update.

Thanks!
