### ISSUE TITLE
Microsoft Dynamics Business Central Help from "Tool Tips?

### ISSUE THREAD

**Issue by csmancini** [MicrosoftDocs/dynamics365smb-docs#13]
When taking the kink from a tool tip on a specific element in BC it takes you yo a general description of the tab with nothing related at all to the specific item with the tool tip highlighted,  for instance when highlighting the tool tip for "Tax Liable Get Help" it takes you to a description for "Register New Vendors" and no definition or explanation for the highlighted term "Tax Liable".  This seems to be a chronic charfacteristic with the get help feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb27fbf6-f6e0-a77e-5b6b-e5051baa58a2
* Version Independent ID: 4ff82855-db32-1774-235f-6c0e3d55bdbf
* Content: [Create a Vendor Card to Register a New Vendor - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/purchasing-how-register-new-vendors)
* Content Source: [business-central/purchasing-how-register-new-vendors.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/purchasing-how-register-new-vendors.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hi csmancini - You are experiencing the intended behavior. 

When you choose the Get help button on a tooltip, the conceptual help topic for the page that the field or action is on opens. There can only be one help topic per page, so the help topic that is most relevant, i.e. best covers the tasks that you perform on the page, will open. 

Because help topics are conceptual and are meant to be complemented by tooltips, this design means that the help topic that opens for a page does not necessarily mention fields and actions on the page. Information about fields and actions is primarily provided by tooltips. 

Regards
Soren, Business Central application writer

**Comment by csmancini** [comment]
Soren,

I understand it is the intended behavior, and the experience is underwhelming to clarify it is less than mediocre.  You should on pass the expression to the organization, it is an easy opportunity for product improvement.

The link from the tool tip fails to link any relevant information for the highlighted tool, like you stated it will open an explanation for the page and not the tool.  Well the explanation like the tool tip lacks detail on the fields and actions contained in the originating page.

So the tool tip provides a as near as irrelevant explanation for the tool or field, as an example Microsoft’s tool tip for a football on the soccer page would be “it’s a ball for feet”

Following it would take you an overview of the soccer page that made no mention of the ball or half of the fields on the referring page.

This is feedback to improve the product.

Chris
