### ISSUE TITLE
Question about cumulative updates

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [MicrosoftDocs/dynamics365smb-docs#149]
Are there no branches or tags for each cumulative update CU1, CU2, CU3 etc.? 
e.g. Since I need the docs for CU2, I'd like to avoid newer features. 
dynamics365smb is a very wide title imho, Will there be a complete different project when BC140 comes?

**Comment by edupont04** [comment]
Hi there,
We do not currently tag the content based on monthly updates because very few new capabilities are rolled out in these service updates. We encourage you to always get the latest version of the docs from our GitHub repos so that you have the latest bug fixes and other corrections, but if you worry about accidentally adding content for capabilities not present in the on-premises version that you are deploying, then you can always use the content on the on-premises installation media.
I hope this answers you question?
