### ISSUE TITLE
Seems not to work

### ISSUE THREAD

**Issue by Andreas78A** [MicrosoftDocs/dynamics365smb-docs#161]
Tried to import items from another Company but no tables are shown to copy (card stays completely empty).

**Comment by edupont04** [comment]
Hi Andreas78A,
I'm closing your Issue because it seems to be about the product functionality rather than the contents of the Help. You might want to check the Dynamics 365 Business Central community forum here in case someone has asked a related question: https://community.dynamics.com/business/f/758
