### ISSUE TITLE
OIOUBL Busniess Central SAAS

### ISSUE THREAD

**Issue by ui2607** [MicrosoftDocs/dynamics365smb-docs#176]
In Business Central 14 saas the description field in sales invoice line (sales line)) has been extended to 100 characters. When you try to create OIOUBL invoice file after the sales order has been posted it comes with this error:

The length of the string is 100, but it must be less than or equal to 50 characters.

**Comment by CorpitalMAS** [comment]
It seems to be because of two procedures in Codeunit 13648 CommonLogic. The text variable PartyName only have 50 characters.

Local procedure InsertCustomerParty(var AccountingCustomerParty: XmlElement; GLN: Code[13]; VATRegNo: Text[20]; PartyName: Text[50]; PostalAddress: Record "Standard Address"; PartyContact: Record Contact);

procedure InsertAccountingCustomerParty(var InvoiceElement: XmlElement; GLN: Code[13]; VATRegNo: Text[20]; PartyName: Text[50]; PostalAddress: Record "Standard Address"; PartyContact: Record Contact);

**Comment by edupont04** [comment]
Closing issue since it's not about the docs.
