### ISSUE TITLE
Create and use your own predictive web service for cash flow forecasts next step

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#177]
How can we then use the Cash Flow Forecast. What is the next step?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea2765e3-713c-d9c9-a545-8b7051ac3b9c
* Version Independent ID: 26ed03b2-9d91-957d-1ada-fd570b8bf993
* Content: [Setting up Cash Flow Analysis - Business Central](https://docs.microsoft.com/en-NZ/dynamics365/business-central/finance-setup-cash-flow-analyses)
* Content Source: [business-central/finance-setup-cash-flow-analyses.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-setup-cash-flow-analyses.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by rubenseishima** [comment]
Hi,

Sorry for taking so long to reply. After setting up the Cash Flow Forecast, the forecast chart can be viewed in the *Accountant* Role Center, choose the **Recalculate Forecast** action to update the chart after the setup or changing settings. Since others might have the same question, we've updated the article and it will be published in the near future.

**Comment by rubenseishima** [comment]
related: #618

**Comment by edupont04** [comment]
Now live in English (US). The update will be available in English (AU) in a week or two.
