### ISSUE TITLE
is this true for AUD / NZ

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#196]
Can this function work in AU and NZ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 995ea036-01a4-4f69-8a9c-1e27ca2dfac9
* Version Independent ID: 1e5bdbff-3fdd-c3cc-d493-5ec9d20444d6
* Content: [Direct Debit Using Domiciliation - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/belgium/direct-debit-using-domiciliation)
* Content Source: [business-central/LocalFunctionality/Belgium/direct-debit-using-domiciliation.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Belgium/direct-debit-using-domiciliation.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hi makdaddy8888,

No, this feature is particular to Dynamics 365 Business Central in Belgium. For more information, see [https://review.docs.microsoft.com/en-us/dynamics365/business-central/about-localization](https://docs.microsoft.com/en-us/dynamics365/business-central/about-localization).

Closing issue.

**Comment by PeterWone** [comment]
@edupont04  You didn't read the question. He didn't ask you _whether_ it works in AU/NZ, he asks whether it _can_ work in Australia or New Zealand, and the answer is that a similar customisation is possible but has not been done, and probably won't be done because the ANZ market isn't large enough to support the cost.

**Comment by edupont04** [comment]
Hi @PeterWone ,
Theoretically and philosophically, any functionality can be built for any market, either by Microsoft or one of our many partners. But the existing functionality for direct debit that was written for the Belgian version cannot be directly replicated for the Australian version due to different requirements and dependencies.
