### ISSUE TITLE
no explanation

### ISSUE THREAD

**Issue by jiggleypodgery** [MicrosoftDocs/dynamics365smb-docs#23]
how exactly are you supposed to use profiles? You can't assign profiles to users as the boxes are greyed out and those belonging to multiple groups seem to get a profile at random.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc54780-19ba-4d44-cd54-3435966b1293
* Version Independent ID: 1417b68c-68fd-9f06-fafa-854edc3c1e75
* Content: [Manage users and roles - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/admin-users-profiles-roles#profiles)
* Content Source: [business-central/admin-users-profiles-roles.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-users-profiles-roles.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! As the note states, in the current version of Business Central, you cannot add, edit, or delete profiles. We have chosen to show the profiles so that you can see which users have access to which Role Centres, and we expect to be able to enhance this experience at a later point.

In the current version, access to different areas is controlled by user groups and permisssions. For more information, see this article: https://docs.microsoft.com/en-gb/dynamics365/business-central/ui-how-users-permissions

I hope this answers your concern. Otherwise, you can submit a request on the Ideas site at https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1
