### ISSUE TITLE
Volume Field

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#231]
There is no information in any Business Central documentation that outlines the 'volume' field in the inventory section of an item card.  What is this and what is the UOM?  Is it in Litres? Cubic Meters, Cubic Feet...Cubic Centimeters?  Where is this figure used? (it's important for freight, absolutely!).  It's the same with Net and Gross weight - what is the UOM?  KG, LBS, Grams, elephants?  How does Volume (if it's product volume in come form of cubic measurement) relate to the carton volume (i.e. where do you put dimensions for a unit of measure?...)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37d63058-5104-f4c6-dd07-21caf3a4a4a8
* Version Independent ID: 6c3e166d-bdc9-b823-dfc4-62957f5aa385
* Content: [Create Item Cards for Goods or Services - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/inventory-how-register-new-items#feedback)
* Content Source: [business-central/inventory-how-register-new-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-how-register-new-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by rubenseishima** [comment]
Hello,

Sorry for the long delay for an answer. The app doesn't set a unit of mass or volume on those specific fields, accepting whichever suits your processes, but we recommend being consistent when using them, since the values are applied—as you already guessed—to shipping, and inventory processes, as the docs cover on [this article about setting up units of measure](https://docs.microsoft.com/dynamics365/business-central/inventory-how-setup-units-of-measure#to-set-up-multiple-item-units-of-measure).

I understand it is not the answer you were looking for when you submitted this issue, but in case you want the app to be stricter about units for those measurements we suggest that you submit a feature request here: https://aka.ms/businesscentralfeedback
