### ISSUE TITLE
Gælder ikke d365 / BC

### ISSUE THREAD

**Issue by MariaFrederiksen** [MicrosoftDocs/dynamics365smb-docs#242]
Man kan ikke på d365 / BC søge Interaktioner. Den henviser alene til dokumentationen her, men ingen menupunkter.
Mvh Maria

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: b44b0359-ebac-60f6-dcb6-628180a15c9a
* Version Independent ID: 2fe7b562-278e-7f43-9f68-cfa9e6ba3ce4
* Content: [Oprette automatisk registrering af interaktioner - Business Central](https://docs.microsoft.com/da-dk/dynamics365/business-central/marketing-auto-record-interactions#feedback)
* Content Source: [business-central/marketing-auto-record-interactions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-auto-record-interactions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hej @MariaFrederiksen,
My apologies for getting back to you belatedly. I'm writing in English so that others will also benefit from this information. 
Interactions are available in Dynamics 365 Business Central and have been for a long while. If you still cannot find the capabilities, then I suspect that you might not have permission to view those pages. You might want to talk to your administrator about making sure you have the right permissions.

Also, you can get an quick overview of the capabilities that you have access to by using the role explorer. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/ui-role-explorer (på dansk: https://docs.microsoft.com/da-dk/dynamics365/business-central/ui-role-explorer)
