### ISSUE TITLE
Creating New Company doesn't start any wizard

### ISSUE THREAD

**Issue by Addice73** [MicrosoftDocs/dynamics365smb-docs#245]
Hi, 

Following the documentation on :
https://docs.microsoft.com/it-it/dynamics365/business-central/about-new-company
I was expecting the wizard to open with this choice

The setup wizard offers three templates:
 - Evaluation - Sample Data
 - Production - Setup Data Only
 - Create New - No Data

Unfortunately this doesn't happen at all.
I'm running a BC15 ONPREM
Version: platform 15.0.36510.0 + application 15.0.36649.0

**Comment by edupont04** [comment]
Hello @Addice73 ,

You are right that the behavior is different in Business Central online and Business Central on-premises when it comes to how you create companies. In the Help we describe how it works in Business Central online where an assisted setup guide helps people add a new company based on three different templates. 
In the default version of Business Central on-premises there are no templates and no assisted setup because on-premises you own the application, the data, and the SQL Server database completely.

**Comment by Addice73** [comment]
Ok but this should be documented, why not?

In data 22 ottobre 2019 15:31:58 Eva Dupont <notifications@github.com> ha 
scritto:
