### ISSUE TITLE
Prevent Order from Shipping or Invoicing?

### ISSUE THREAD

**Issue by mstallmann** [MicrosoftDocs/dynamics365smb-docs#25]
It says above to enter a hold code on a posted ledger entry.  Not sure how that will block a shipment or invoice, since the shipment is what creates the ledger entry.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa21c110-7197-9f9d-be23-b2629400aafe
* Version Independent ID: 4f8067b6-2590-e866-f8fe-bd19136346b4
* Content: [How to Manage Customer Credit Information - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedstates/how-to-manage-customer-credit-information#to-add-comments-to-customer-credit-information)
* Content Source: [business-central/LocalFunctionality/UnitedStates/how-to-manage-customer-credit-information.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/UnitedStates/how-to-manage-customer-credit-information.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thanks for the input, mstallmann, 

I have removed the topic as it was not unique to US, the On Hold description was incorrect, and because the functionality is already described here: 

https://docs.microsoft.com/en-us/dynamics365/business-central/receivables-collect-outstanding-balances
https://docs.microsoft.com/en-us/dynamics365/business-central/receivables-how-block-customers
(Will be available in one week)

Regards, Soren
