### ISSUE TITLE
Customize sync'ed fields

### ISSUE THREAD

**Issue by wikap** [MicrosoftDocs/dynamics365smb-docs#261]
Hi 
How do you customise the individual field mappings in the sync engine
1) I would like Debitor Number in BC to go into Account Number in CRM
2) I would like to take a custom field in CRM to go into a field in BC
?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55b85584-39d9-f25a-4647-2f230e8e6db2
* Version Independent ID: 7cb5bff0-ae9f-bf03-15d3-919a6c9a4aa8
* Content: [Modify Table Mappings for Synchronization - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-to-modify-table-mappings-for-synchronization#feedback)
* Content Source: [business-central/admin-how-to-modify-table-mappings-for-synchronization.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-to-modify-table-mappings-for-synchronization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by hkusulja** [comment]
I did not find (documented) way, how to insert new rows in table for Field Mappings...

**Comment by rubenseishima** [comment]
Hi,

Apologies for replying after this long. Since this issue was posted, the docs were expanded, both the [original article about table mappings](https://docs.microsoft.com/dynamics365/business-central/admin-how-to-modify-table-mappings-for-synchronization), and additional walkthroughs on the Administration content including one on how to [customize the field mappings between Business Central and Dataverse](https://docs.microsoft.com/dynamics365/business-central/dev-itpro/administration/administration-custom-cds-integration) that I believe cover your questions. Also, users in the BC community have additional experience to share about the Sales integration: https://community.dynamics.com/business

**Comment by edupont04** [comment]
Closing as fixed.
