### ISSUE TITLE
Cannot find Sales Cycles Page

### ISSUE THREAD

**Issue by redware** [MicrosoftDocs/dynamics365smb-docs#277]
Looking to change the sales cycles on opportunity and finding that opportunity_salesstage does not appear in the optionsets list - but when I search for SALES CYCLES it does not show up... what am I missing ? I see also we need to change salesstage and processtage_category but maybe once I find the sales cycles page it will do it all for me. Where is the SALES CYCLES page please ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859e3edd-bc18-3a56-9c31-8b28f30caf2d
* Version Independent ID: 962db0bb-a60c-ae2a-1d20-8d272b74eec4
* Content: [Set Up Opportunity Sales Cycles and Cycle Stages - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/marketing-how-setup-opportunity-sales-cycles-stages#feedback)
* Content Source: [business-central/marketing-how-setup-opportunity-sales-cycles-stages.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-how-setup-opportunity-sales-cycles-stages.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

Sorry for the delay on this. I tried entering *sales cycle* and *sales cycle stages* in the **Tell me** box in Business Central 2021 release wave 2 (version 19). It does return the **Sales Cycles** page for me. I'm not sure whether a fix was made since this issue was created. I will close this issue for now, but if you are still experiencing problems, or I have misunderstood something, let us know and we'll reopen it.
