### ISSUE TITLE
Other countries...?

### ISSUE THREAD

**Issue by benmarriott-TVT** [MicrosoftDocs/dynamics365smb-docs#290]
Is there not standard guidance on payment terms for other countries

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f0109b5-e9f8-5537-d13d-5f3c6f9cb8cf
* Version Independent ID: 669e2224-0f43-e744-d313-ff1d72d4fff2
* Content: [Setting Up Payment Terms - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/italy/how-to-set-up-payment-terms)
* Content Source: [business-central/LocalFunctionality/Italy/how-to-set-up-payment-terms.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Italy/how-to-set-up-payment-terms.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Our apologies for the delay in getting back to you on this, but in general, we do not provide strict guidance for how to set up payment terms because this is typically very different from country to country and from company to company. However, in Italy there are particular requirements for calculation, which is why we have this article.
