### ISSUE TITLE
Your Microsoft partner can extend it for you again: How ?

### ISSUE THREAD

**Issue by srenders** [MicrosoftDocs/dynamics365smb-docs#309]
Regarding this piece of text:
"_Extending the trial period yourself is a one time-thing though. You cannot extend it twice, at least not yourself. If you have already extended the period, your Microsoft partner can extend it for you again. That's also a one-time thing._"

What is the exact procedure to do this? I have had several questions from companies evaluating Business Central that got stuck here then after a lot f searching and googling contacted a partner, and that partner did not even now how to extend a trial. 

Than I have also heard partners ask questions about this procedure, most of them don't even know how to do this.

Would it be possible to document this a little more, with some clear steps that describe what a company and a partner exactly need to do to extend a trial, that was already extended once by the user? This would avoid a lot of confusion and frustration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dffd5471-dbdb-80b8-56a5-0d6e921eff9f
* Version Independent ID: 9f44b4ef-8069-5747-a78b-a85152996b55
* Content: [Extend Your Trial Version - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-extend-trial)
* Content Source: [business-central/admin-extend-trial.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-extend-trial.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hi Steven,
We have described this in the administration content here: 
[https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-administration#extending-trials](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-administration#extending-trials)

**Comment by srenders** [comment]
Hi Eva,

I'm sorry but it is still unclear.
It says:
_

> If the prospect wants to extend the trial further than those 30 days, the partner can extend it another 30 days if the administrator, acting as the delegated administrator, log into the prospect's Business Central and extend the trial using the same Extend Trial Period guide.

_ 

What's the exact procedure then? 
If a user has created an Office 365 Trial account and with that Office Trial account has created the Business Central trial, how can a partner then login as a delegated admin and extend the trial? Dos that work for Office 365 trials?

Other scenario, a user uses their own email address to create a trial, and it's not an Office 365 email address, how can a partner then login as a delegated admin?

Also a user who has a trial, that needs to be extended by a partner, does not want to loose their data. So if a partner proposes to followthe procedure described here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/demo-environment then the customer would have to start all over again from scratch.

Then the last option, contact support, how exactly does that need to happen? When the user goes to the Admin Center and creates a normal support ticket they get no response, so do they need to create a ticket for a production outage instead?

I don't want to nag about this, I'm simply forwarding a message I receive from potential customers and existing partners, that it does not work and they can not figure out how it works.

**Comment by edupont04** [comment]
Hello again Steven,

We have tried to make it clearer now by adding See Also links to this article: 
https://docs.microsoft.com/en-us/dynamics365/business-central/admin-extend-trial#see-also

We have also added some links to the overview here: 
https://docs.microsoft.com/en-us/dynamics365/business-central/across-preview

And we have elaborated on the administration aspect here:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-administration#extending-trials

It all boils down to what the trial is being used for and why it must be extended two times or more. We believe that the free trial is a very important aspect of getting started with Business Central, but we also believe that interested parties should grab hold of a partner as soon as possible since it's complicated stuff, this sort of software. 

We also continue to work with the partner community to help them get started with Business Central online, and you yourself play an important role in that work as well. So if you hear that some process appears to be broken, do let us know!

**Comment by srenders** [comment]
Hello Eva,

Thank yo for the extra links, but as I feared, partners still don't know how to do this.
I was contacted again by a prospect, evaluating BC. They contacted a partner to extend their trial, and the partner explained them that they do not know how to do that.

I personally think it might be a good idea to create a step by step procedure in the BC docs, including screenshots, on how to do this. Providing links to other websites get's people lost in the forest of documentation ;)

Greetings,
Steven

**Comment by edupont04** [comment]
Hello again Steven,
Thank you for your feedback! The step-by-step instructions are actually already there, but we're working on an update to make it a bit more explicit, including clarifications in this article about Office 365 trials, why they need a partner if they want more than 60 days of trial, and what the partner must then do (=establish reseller relationship so they can get a delegated admin account so they can log in and run the same wizard). Also, the wizard is only available through the notification bar. So if the user dismisses that notification, they have to trigger the notification to show again.

As I wrote above, it all boils down to what the trial is being used for and why it must be extended two times or more. There will always be many scenarios and variants that we do not mention in the docs because they apply to a tiny subset of our customers or partners. But we strive to have content that serves as entry points for everyone, including this article and its very close cousin in the admin docs:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-administration#extending-trials

**Comment by faridjalal** [comment]
Ok, we are a Microsoft Partner that managed to get this working late on a Friday afternoon :) 

**A Partner user that satisfies these 2 conditions should attempt the Extension.**

1. Has Delegated Admin access to client's BC environment (users with Admin Agent / Helpdesk Agent role in the Partner Center are granted Global (Delegated) Admin access in the client's Azure AD tenant)
2. NOT already on the client Azure AD as a Guest user (when a partner user is added as a guest to the customer's Azure AD, they can no longer log in as a Delegated Admin into the client's BC environment)


**Step 1**

EITHER

1. Go to Microsoft Partner Center Dashboard https://partner.microsoft.com/en-us/dashboard
2. Select CSP > Customers > Client
2. Select Service Management > Administer Services > Dynamics 365 Business Central 
3. This will prompt you to login using your account into the client's BC environment 
 
OR

Simply navigate directly to the Business Central Admin Center (include the domain or the Azure Active Directory ID of the customer in the URL).
https://businesscentral.dynamics.com/contoso.com/admin OR
https://businesscentral.dynamics.com/yyyyyyyyy-xxxx-zzzz-yyyy-zzzzzzzzzzzz/admin


**Step 2**

Once logged into client's BC successfully as the Delegated Admin, navigate to the below URL to launch the Extension wizard.
https://businesscentral.dynamics.com/contoso.com?page=1828 OR
https://businesscentral.dynamics.com/yyyyyyyyy-xxxx-zzzz-yyyy-zzzzzzzzzzzz?page=1828


**Step 3**
 
If you get an Unauthorized error, you do not have Delegated Admin access to the client's BC environment or are a guest user on the client tenant.

DO NOT click 'Continue to Business Central' - this is a red herring and will take you down a couple of unhelpful loops. Instead, repeat the above step(s) but with a user that satisfies the 2 conditions.


https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/delegated-admin

Drop us a line at www.walkerscott.co if you need help with this ;)
 
Cheers!
