### ISSUE TITLE
On the Item Picture Card - Take Picture , Error message

### ISSUE THREAD

**Issue by AndyJMGeer** [MicrosoftDocs/dynamics365smb-docs#315]
Using browser client latest Edge,
Media Object cannot be imported because the instream object is empty.

**Comment by AndyJMGeer** [comment]
Version: GB Business Central 16.0 (Platform 16.0.11233.11665 + Application 16.0.11209.0)

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support or submit a feature request . For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem) and [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback).
