### ISSUE TITLE
The "App Monetization Demo Guide" link is not working

### ISSUE THREAD

**Issue by jpagessummar** [MicrosoftDocs/dynamics365smb-docs#320]
Hello
The "App Monetization Demo Guide" link is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed34ba95-a843-90b0-dd51-c24023ccd9d2
* Version Independent ID: 43259fda-960d-bd7a-97c6-74f569a54e11
* Content: [Developers learning catalog - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/readiness/readiness-learning-developers)
* Content Source: [business-central/readiness/readiness-learning-developers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/readiness/readiness-learning-developers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @loreleishannonmsft
* Microsoft Alias: **v-lshann**

**Comment by edupont04** [comment]
Hello jpagessummar,

Thank you for your feedback! The link appears to be broken because it points at the Dynamics Learning Portal and requires PartnerSource access. We have identified that there are currently problems with links pointing from the Docs.microsoft.com to PartnerSource/CustomerSource but have not found a sustainable solution yet. 

The workaround is to copy the link and paste it into the address field in another browser tab. This is the  link you want: https://mbspartner.microsoft.com/secure/coursematerials/D365/Standalone/AppMonetizationDemo.zip

**Comment by kontax85** [comment]
Hi Eva,
if i'm not mistaken, this is the current result of that link:
![image](https://user-images.githubusercontent.com/12779310/80129851-f67a7d80-8597-11ea-86e0-816fbee31a02.png)

Thank you, best.

**Comment by edupont04** [comment]
Hello kontax85,

The team that owns the PDF and ZIP files is investigating what happed to them.

**Comment by it-ribe** [comment]
Hi Eva
Any news on this link? :-)

**Comment by edupont04** [comment]
Hello @it-ribe 
Nothing yet, as far as I know. You might want to reach out to Cloud Ready Software who initially created the demo app if you can't wait for my colleagues to get back to us.

**Comment by gregoryvolkov** [comment]
Any news here?

**Comment by it-ribe** [comment]
Hi got it from a partner on yammer.
Here is a share
https://www.dropbox.com/s/t7s9t393b5hr6dx/AppMonetizationDemo.zip?dl=0

**Comment by gregoryvolkov** [comment]
Awesome. Thanks for sharing! BTW, there are so many other broken links at Microsoft...

**Comment by edupont04** [comment]
Hi everyone,
The original document is no longer available on Microsoft.com. You can vote for this suggestions: https://experience.dynamics.com/ideas/idea/?ideaid=8a736a33-0937-ea11-8454-0003ff689f0d
