### ISSUE TITLE
What is difference between companies and envrionments

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-docs#335]
Please document mora details on, how it is different to have multiple environments (databases) on same tenant versus more companies inside the same environment.

What data / settings are shared on the same environment between multiple companies?

Can some data (like, customers, vendors, products) be shared between companies on the same environment?
Are the extensions and localization installed on the environment level, or on company level?

Also, please explain best practice for example scenario:
1. One organization, one company, one tenant, one environment with one company, all i region - (example Croatia, Europe)
2. Organization register and opens another new company in another region (example USA). It will use the same (original) Azure AD tenant, with same users and BC licenses.

What should organization do for the new USA company?
Option A:
Create a new company inside existing environment? Disable extensions for Croatian localization. Install additional extension (w1?) for USA company?
Option B:
Create a new environment for USA company, with different environment region (US) with only one company, and preinstalled (w1) extensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67aa887f-f6d3-890b-5d50-d4ccbb4b6423
* Version Independent ID: 2e176733-990f-85a4-f959-cc511012e99a
* Content: [Create new companies using an assisted setup guide - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/about-new-company)
* Content Source: [business-central/about-new-company.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/about-new-company.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello @hkusulja,
Thank you for your feedback! This is not an easy question to answer because, as you imply yourself, it depends on the organization's needs. You can get a hint at the answer in the note in this article: https://docs.microsoft.com/dynamics365/business-central/finance-how-report-vat

Essentially, an environment maps to a country, and a company maps to a business entity, such as subsidiaries. So in your example above, the answer is option B: You need a separate environment for the additional country. Each environment comes with local functionality for that particular country, and you cannot mix localizations due to the potential conflicting tax reporting, for example.
We'll make this a bit clearer in the next doc refresh.

**Comment by hkusulja** [comment]
@edupont04  ok, so that answers the question and docs can be updated, that microsoft recommendation is to have one environment per country due to localization restrictions and not possible to intermix more localizations for different countries.

**Comment by edupont04** [comment]
Yes, that is how things work - if you came to Business Central from Dynamics NAV, then it works essentially the same way there. Of course, you can have multiple environments that are all based on the same country version, but you cannot have companies in the same environment and be able to report taxes to more than one country in a compliant way.

**Comment by hkusulja** [comment]
ok, thank you for clarification, it would be nice to update BC docs with that info to avoid future confusion for new users.

**Comment by edupont04** [comment]
This will be fixed in the next doc update.
