### ISSUE TITLE
Read-Only Scale Out

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#354]
Hello 

Can you please add some more information on the Read-Only replica database for reports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7042465-a135-e0f1-9f60-c0cfc0cc5379
* Version Independent ID: 381744ba-c6b6-84ee-8966-69efc9136d7d
* Content: [Administrative tasks in Business Central - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/admin-setup-and-administration)
* Content Source: [business-central/admin-setup-and-administration.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-setup-and-administration.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hi Ben,

Sorry for the late response, but we're short-staffed these days. I assume that you are talking about the possibility to have a read-only copy of your data from an on-premises deployment of Business Central? or are you talking about the read-sale-out that developers can set in code and that you can set on an on-premises SQL Server but is built in for Business Central online?
The latter is talked about [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/database-read-scale-out-overview) and [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/performance/performance-developer#using-read-scale-out).

The former is talked about here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/faq-intelligent-cloud

**Comment by makdaddy8888** [comment]
That’s ok thanks for responding.

I was referring to the read-only copy of data. I heard about this option being available. Is it only available onpremise?

Kind Regards
Ben Opit
+61411707070

**Comment by edupont04** [comment]
Hi Ben,
Again, I apologies for the delay in following up. Yes, the idea behind this feature is to be working on-premises but have a read-only copy in the cloud so that you can use the various insights that you can get from running in the cloud. Since you are already using Business Central online, maybe you could create a sandbox environment based on production? For more information, see  https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/environment-types

Closing the issue.
