### ISSUE TITLE
Apply Usage Link

### ISSUE THREAD

**Issue by DaveBoehmPBSI** [MicrosoftDocs/dynamics365smb-docs#38]
This functionality looks interesting.  Unfortunately I don't see it on my "Jobs Setup" page or on the job cards.  I have an "Essentials" subscription.

Questions:
Is this available only on a Premium subscription?  Is there any document that describes what features are available per subscription.  Perhaps in this "Get Help", you could use a different background shade to differentiate between features that are available only in Premium.

Is this something that is listed in the "Get Help", but really won't be available until the October 2018 release?  I've seen where the documentation seems to get ahead of what actually exists in the current version of the product.  Once again, perhaps in this "Get Help" you could use a different background shade to indicate something that is documented, but not yet actually available in the current edition of BC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2441c40-593b-51fa-fb05-c49592a3b456
* Version Independent ID: 4b438402-bc82-98ef-26bc-8dc55c9a7ea4
* Content: [Set Up Jobs Prices and Job Posting Groups - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/projects-how-setup-jobs)
* Content Source: [business-central/projects-how-setup-jobs.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/projects-how-setup-jobs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hi Dave - Thank you for the feedback, and your ideas for "versioning" of Help. 

The Apply Usage Link by Default check box may have been inaccessible because of the know issue described as the last FAQ item here: https://docs.microsoft.com/en-US/dynamics365/business-central/across-faq. It will certainly be visible in the Jobs Setup window in the October release.

Granted, over the last year, Help has "been ahead" of the product in some sections. This is partly because of the above known issue and partly because we increased Help to the full feature scope when the Sandbox option became available. See Blog post at the time: https://community.dynamics.com/business/b/financials/archive/2017/11/14/new-capabilities-in-finance-and-operations-business-edition-november-2017-now-with-videos  

Concerning versioning: For a while, we maintained notes at the top of all Premium-feature topics, but it was costly to maintain due to frequent changes in experience scoping/product packaging. Another issue is that tagging of content per Microsoft's generic product will likely not match the experience scoping in partner solutions and hence will be a cost in help customization. As for product bits, writers must ensure that the generic help content supports easy customization for partner solutions. For simplicity and customizability, we have decided to not tag feature descriptions per experience setting. Instead, Help assumes Premium experience, meaning that all features are described in full. This is clearly communicated to readers in several high-level topics (available with the October update).

PS: The check box is renamed in Help to Apply Usage Link by Default.

Regards
Soren, Business central application writer

**Comment by DaveBoehmPBSI** [comment]
I’m sorry to hear that it is so expensive to indicate include version information, or mark documentation as being germane to a future release of BC.

As a second suggestion, perhaps you could put document the as yet unreleased functionality in a second “Help”, accessible from the generic “Get Help”.  If the other suggestions are too costly, then I suppose this will be deemed too costly as well.

In any event, I wonder if you realize how detrimental inaccurate documentation is?  In some cases, misleading documentation is actually worse than no documentation at all.  Considering the confusion caused by the current approach, it seems as though the added cost would certainly be justified.

--Dave--

David Boehm, CPA
PBSI
www.pbsisoftware.com<http://www.pbsisoftware.com/>
to book an appt.: https://outlook.office365.com/owa/calendar/ProfessionalBusinessSoftwareInc@pbsisoftware.com/bookings/
Office: 817.752.3352 <tel:817.752.3352>
Cell: 214.392.4797<tel:214.392.4797>
***********************************************************
This communication, along with any documents, files or attachments, is intended only for the use of the addressee and may contain legally privileged and confidential information. If you are not the intended recipient, you are hereby notified that any dissemination, distribution or copying of any information contained in or attached to this communication is strictly prohibited. If you have received this message in error, please notify the sender immediately and destroy the original communication and its attachments without reading, printing or saving in any manner. Thank you.

**Comment by SorenGP** [comment]
Thanks again for your feedback. Help/UI mismatch will be minimal after the October release as all UI elements will be available (see above FAQ item). In addition, the Essential/Premium split will be much simpler: All features will be accessible with Essential except Service Management and Manufacturing, which require Premium. Help topics for these modules will have a text note to that effect.
