### ISSUE TITLE
Walkthrough links to NAV

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#380]
The walkthrough link applies to NAV, even though it’s linked from business central.  Is the walkthrough applicable to BC? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3794279c-6009-ef56-1bfd-722a4fac3610
* Version Independent ID: bfaad14b-12ab-369b-f6e9-c96123be82c9
* Content: [Workflow - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/across-workflow)
* Content Source: [business-central/across-workflow.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-workflow.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update. The current recommendation is that people consider using Microsoft Power Automate if the predefined templates are not enough: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-no-code
