### ISSUE TITLE
What about Shipment from Sales Invoice?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-docs#381]
If we sell merchandise by using Sales Invoice, and we Post Sales Invoice.
How can we after create/post Shipment (document/entity) ?

Without having to have Sales Order (and from there just Post Shipment)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6feb0814-c0a1-151b-8565-a7c60a6ca064
* Version Independent ID: 8f5aed4f-267e-b41f-0a04-a24925d6b220
* Content: [How to Ship Items - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/warehouse-how-ship-items)
* Content Source: [business-central/warehouse-how-ship-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/warehouse-how-ship-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! You are right that the posting of a sales invoice assumes that you are shipping the full quantity at the same time. This is hinted at with the sentence "You use sales orders if your sales process requires that you can ship parts of an order quantity, for example, because the full quantity is not available at once." in this article: https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-sell-products  

We'll make this a bit clearer in the next doc refresh.

**Comment by hkusulja** [comment]
@edupont04 ok, but it is not clear how to get "shipment" document, after the "sales invoice" is posted (all line items are sent in full quantity), but without using sales order.
Let's say, someone skips the sales order > make shipment proces.., and just do the sales invoice. How can you create shipment document, after posted sales invoice?
Thank you

**Comment by edupont04** [comment]
That's what I was saying: When you post the invoice, that's it. The way things work today, you cannot then create a shipment from that posted invoice.  Alternatively, you can look into warehouse shipments.

**Comment by hkusulja** [comment]
Ok, it would be good to update docs with that info for new users. That shipment/receipt is possible only from order, and not after posted invoice.
