### ISSUE TITLE
Don't see an Operations Action

### ISSUE THREAD

**Issue by MarkCWEV** [MicrosoftDocs/dynamics365smb-docs#397]
I don't seem to have an operations action and don't see any way to add the standard tasks

Using: US Business Central 16.2 (Platform 16.0.13440.14360 + Application 16.2.13509.13619)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d707caf5-88d8-58fe-47ab-9c49e565d660
* Version Independent ID: c0fb4a69-e5f3-6dfc-b72e-4214b3f42ffe
* Content: [How to Set Up Standard Tasks for Operations - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/production-how-set-up-standard-routing-lines)
* Content Source: [business-central/production-how-set-up-standard-routing-lines.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/production-how-set-up-standard-routing-lines.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! In the current version of Dynamics 365 Business Central, you must choose the "More options" action to see the "Operations" action. We do not mention this explicitly in the docs, since some users have pinned the "more options" task bar and always see all actions, while others haven't (yet).

I hope this unblocks you. Otherwise, please let us know.

**Comment by MarkCWEV** [comment]
Hi Eva

I have more options selected. Only thing in the Action group is “functions” and that only has copy routing

[cid:image001.png@01D654FB.DC083C20]

**Comment by edupont04** [comment]
Hi Mark,

OK, the step refers to the actions for the routing lines, not the routing itself. Move down to the Lines section, hit "More options", and then you should be able to see the Operation action.
