### ISSUE TITLE
No link to a page for the Requisition Worksheet

### ISSUE THREAD

**Issue by kimberley523** [MicrosoftDocs/dynamics365smb-docs#399]
Hello
Our partners are recommending that we try using the requisition worksheet, I've been able to get it to work the way I would like so came out here to see what the documentation says. However, it appears that the documentation link to that page has been disabled. Is there a page for that function or is it being updated perhaps?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a1e612f-36b8-3fcc-cdc5-886b6908eada
* Version Independent ID: f43fae8f-3f10-aaa8-ee54-20f6e08230e1
* Content: [Supply Planning - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/production-planning)
* Content Source: [business-central/production-planning.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/production-planning.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! Currently, the only guidance we have for the Requisition Worksheet page is what we write in this article: "Run the requisition worksheet to automatically create a detailed supply plan to cover demand for items that are replenished by purchase or transfer only.". Due to the summer vacations, I can't check with a colleague to find out more, but I can see in the internal notes that there weren't any plans to add more content, and that the Requisition Worksheet page is indeed hooked up with this article on purposes.

**Comment by edupont04** [comment]
Hello again,

We've extracted a basic explanation and published it today.
