### ISSUE TITLE
Add first availability

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-docs#404]
It would be very helpful if you could add from which version on specific features are available.
E.g. to unhide page parts, you need BC 16 at least: https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave1/dynamics365-business-central/unhide-parts-page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc9174f7-cad5-7550-b93b-036158d40e38
* Version Independent ID: 8e4dabaa-c112-6a2e-dc18-933253579927
* Content: [Personalizing Pages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-personalization-user)
* Content Source: [business-central/ui-personalization-user.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-personalization-user.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello Natalie,

Thank you for your feedback! The content on Docs.microsoft.com generally reflects the latest version of Dynamics 365 Business Central unless a different version is explicitly specified. I'm leaving this Issue open for a couple of weeks, because I'm heading out on vacation, and might accidentally think about your feedback and come up with a solution, because you're not the first to ask.

**Comment by NKarolak** [comment]
Okay, then have a great vacation 🙂

**Comment by NKarolak** [comment]
Please compare with https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-object#systemid :-)
![image](https://user-images.githubusercontent.com/34504100/88667370-925cdd80-d0e1-11ea-8745-63cb45cfb229.png)

**Comment by edupont04** [comment]
I'm closing this loop now after 2 years because I believe we have, generally speaking, become better at stating when something became available. However, in the business functionality content, it's less straightforward than in the dev/admin docs, because most changes are a tiny edit to existing content or an alternative to existing functionality that will exist side-by-side for a while.
If you disagree, then do let the team know :-)
