### ISSUE TITLE
references VAT instead of GST in Aus localisation page

### ISSUE THREAD

**Issue by nimaladasa** [MicrosoftDocs/dynamics365smb-docs#414]
Needs fixing 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80060536-71c7-8bf9-b5b0-e52a69384a99
* Version Independent ID: cb821276-c3d6-4759-7649-01ff117d14a8
* Content: [How to Set Up Goods and Services Tax Posting - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/australia/how-to-set-up-goods-and-service-tax-posting)
* Content Source: [business-central/LocalFunctionality/Australia/how-to-set-up-goods-and-service-tax-posting.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Australia/how-to-set-up-goods-and-service-tax-posting.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello, 
Thank you for your feedback! I've marked this as Won't Fix because the terminology is correct in the English (Australian) version of the article: https://docs.microsoft.com/en-au/dynamics365/business-central/localfunctionality/australia/how-to-set-up-goods-and-service-tax-posting
 
All our content is authored in English (United States) and often refers to the names of pages by their non-language-specific captions, such as the VAT Posting Setup page. When the content is then translated into the relevant languages, these captions are updated accordingly so that VAT Posting Setup becomes GST Posting Setup for English (Australian). We realise that this can be confusing for some users, but the current behaviour is intentional.
