### ISSUE TITLE
Debit - Credit in ledger entries

### ISSUE THREAD

**Issue by CurabisMartin** [MicrosoftDocs/dynamics365smb-docs#423]
Is it possible to set up a debit- and a credit column in the ledger journal? 
Today, there is only the "Amount" field, but field 14 is Debit Amount and field 15 is Credit Amount. However, it is not possible to add these fields in a customization.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 1814e2a4-7a9a-4ab7-7c22-db275545efff
* Version Independent ID: b05838af-52c6-1f89-d612-3412ada99d7b
* Content: [Bruge finanskladder, der skal bogføres direkte til Finans - Business Central](https://docs.microsoft.com/da-DK/dynamics365/business-central/ui-work-general-journals)
* Content Source: [business-central/ui-work-general-journals.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-work-general-journals.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,


Thank you for your feedback! The decision whether to show only amounts or also show debit/credit amounts is specified by the Show Amounts field in General Ledger Setup. Since this is a company-level decision, the fields cannot be added through personalization.

Closing the issue since it's about product functionality rather than about the docs.
