### ISSUE TITLE
Page No Longer Available in Current Version of Business Central.

### ISSUE THREAD

**Issue by saubermfg** [MicrosoftDocs/dynamics365smb-docs#424]
It appears that Production BOM is no longer accessible from the search box, or by expanding the "Role Explorer" page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 116dcd57-f002-5963-71e6-da6db354ec07
* Version Independent ID: 50141a0e-bc99-4f41-8838-e17611181f76
* Content: [How to Create Production BOMs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/production-how-to-create-production-boms)
* Content Source: [business-central/production-how-to-create-production-boms.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/production-how-to-create-production-boms.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/dynamics365/business-central/product-help-and-support#report-a-problem). Note that the availability of production BOMs may rely on your license type and/or your permissions.
