### ISSUE TITLE
Why are some UI elements that I used in Dynamics NAV not visible in Business Central?

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#43]
"A few complete features, such as Comments, are currently being optimized for the web client and are, therefore, not available in Business Central." 
The sentence would make more sense if instead of "Web Client" there would be "Windows Client".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79ad74cc-aba8-7c05-93c2-da28efdbf375
* Version Independent ID: 2f07a9a9-4cf3-c835-29d0-aab1c830277c
* Content: [FAQ About Using Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq)
* Content Source: [business-central/across-faq.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! The statement is correct because the main client for Business Central is the browser experience (also known as the web client). For online customers, this means that certain functionality is not available because they require the legacy Dynamics NAV client connected to Business Central (also known as the Windows client).
