### ISSUE TITLE
Payroll Support / Integration in UK?

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/dynamics365smb-docs#432]
Hi,

Is there a Payroll feature in Dynamics 365 (Business Central or otherwise)?

I understand that there's support to [Import Payroll Transactions](https://docs.microsoft.com/en-gb/dynamics365/business-central/finance-how-import-payroll-transactions), but, I'm thinking about using Business Central as a Payroll software.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7dcf603-9deb-1715-9e2f-9afbd791498e
* Version Independent ID: 955ab2fc-93cc-3e63-b7c9-e5b34f944642
* Content: [United Kingdom Local Functionality - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedkingdom/united-kingdom-local-functionality)
* Content Source: [business-central/LocalFunctionality/UnitedKingdom/united-kingdom-local-functionality.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/UnitedKingdom/united-kingdom-local-functionality.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Dynamics 365 Business Central can import payroll information from specialized services such as Ceridian: https://appsource.microsoft.com/en-gb/product/dynamics-365-business-central/PUBID.microsoftdynsmb%7CAID.af108c30-ac89-4ed1-a98e-15708e0ee7f6%7CPAPPID.30828ce4-53e3-407f-ba80-13ce8d79d110?tab=Overview

Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)

**Comment by haneef95** [comment]
Thanks.

Any integration with services like [Payroo](https://www.payroo.com/)?

Thanks
