### ISSUE TITLE
Why perform one action vs another? (posting to resource journal vs job journal)

### ISSUE THREAD

**Issue by ilyalehrman** [MicrosoftDocs/dynamics365smb-docs#442]
Technical documentation isn't really useful - for a complex product - unless it answers the question WHY. For example, on this page, there are two sections at the end, "To post time sheet lines in a resource journal" and "To post time sheet lines in a job journal".  WHY WOULD I PICK ONE VS THE OTHER? In what circumstances should i post time to a resource journal? when should i post to a job journal? Why would I make that decision? How does this affect billing for a project? Does it? Where do I go to find more information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd49f3e2-3072-8a24-dcba-bc7aaba2625d
* Version Independent ID: 00d7ace5-1e2a-7eab-ee6c-de453653635a
* Content: [Work with Time Sheets for Jobs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/projects-how-use-time-sheets)
* Content Source: [business-central/projects-how-use-time-sheets.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/projects-how-use-time-sheets.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! I'm sorry to hear that our documentation caused confusion and frustration, since that is definitely not our goal. Rather, the documentation tries to reflect the non-prescriptive nature of the software. Many organizations have a clear preference for how to carry out many tasks, and Dynamics 365 Business Central often supports two or more ways of doing things. 

In this particular example, you can post the time sheet lines in two different journals. If you prefer to track cost by resource, then you might prefer to use the resource journal. If you prefer to track cost by project, then using the job journal might make more sense.  

You can learn about project management and the Jobs functionality here: 
[https://docs.microsoft.com/en-us/learn/paths/create-jobs/](https://docs.microsoft.com/en-us/learn/paths/create-jobs/)
[https://docs.microsoft.com/en-/learn/paths/calculate-post-job-wip/](https://docs.microsoft.com/en-us/learn/paths/calculate-post-job-wip/)
