### ISSUE TITLE
Create Contact Cover Sheet Action

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#444]
Can you please help share what this action does?
What are these for?

**REMARKS**

- As agreed upon
- For your information
- Your comments please
- For your approval
- Please call
- Returned after use

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9dfad9-d584-63b7-833c-e11e27fbd137
* Version Independent ID: 4dceddc3-c9a4-5c40-4def-4b3e468ba36a
* Content: [Relationship Management - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-relationship-management)
* Content Source: [business-central/marketing-relationship-management.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-relationship-management.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Essentially, when you create an interaction with a contact, you can print or send a cover sheet. The fields that you ask about are automatically printed as part of the cover sheet and are marked with an X on the printed form if you select the field in the request page. The fields are intended as predefined standard fields for interactions with your company's contacts, and they are defined in code, sadly, in the ContactCoverSheet.Report.al file. The Interactions functionality with its cover sheets is not our best designed or documented area. Most of the customization capabilities in this area require coding, which is why our docs are rather vague and hand-wavy, I'll admit.
