### ISSUE TITLE
Action -> Item -> Identifiers

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#448]
Hi 

I think this action item identifiers button needs some documentation. Page 7006 looks like this function only works if deploying handheld devices? And cannot be used outside of ADCS.
 
I was assuming I could setup item identifiers to create a warehouse carton configuration and show availability by this identifier but I don't think that is the case.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de056a84-519d-7e62-1250-e8cc230e4016
* Version Independent ID: 3af33f17-b156-d966-8619-2ad2fd2823b7
* Content: [Use Automated Data Capture Systems (ADCS) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/warehouse-use-automated-data-capture-systems-adcs)
* Content Source: [business-central/warehouse-use-automated-data-capture-systems-adcs.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/warehouse-use-automated-data-capture-systems-adcs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Item identifiers are designed to work with ADCS and handheld devices only. 

As it says in the article: Each warehouse item that you want to use with ADCS must be assigned an identifier code to link it with its item number. For example, you can use the item's bar code as the identifier code. An item can also have multiple identifier codes. You may find this useful in the case where an item is available in various units of measures, such as pieces and pallets. In this case, assign an identifier code to each.

I hope this answers your question. Otherwise, do let us know.
