### ISSUE TITLE
Reverse Charge VAT in UK for CIS

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-docs#475]
Just wondering if there is any information on setting up reverse charge VAT for [CIS](https://www.gov.uk/guidance/vat-domestic-reverse-charge-for-building-and-construction-services) (Construction Industry Scheme) and how to show the correct information on the Sales documents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e7f2fb3-10db-763b-c1dd-e9d8e3ec0070
* Version Independent ID: c7cdf2cb-38fe-8eeb-d9fb-cfeb79acc5e6
* Content: [How to Set Up Reverse Charges on VAT - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedkingdom/how-to-set-up-reverse-charges-on-vat)
* Content Source: [business-central/LocalFunctionality/UnitedKingdom/how-to-set-up-reverse-charges-on-vat.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/UnitedKingdom/how-to-set-up-reverse-charges-on-vat.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! As you can see, we don't usually have detailed guidance for how to set up Business Central for specific reports and similar because that can be very dependent on specific industries or locations, for example. If you think there is a need for more detailed guidance for setting up reverse charge VAT based on CIS, you can submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback). Choose the "Documentation" category, and the suggestion will be forwarded to our team.
