### ISSUE TITLE
Code examples needed

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-docs#483]
Are there any How To or Walk Through topics to demonstrate this with a custom code unit? If not, I would like to suggest the same. Thanks...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fcb95cd-fd17-03c1-d52b-368c37671df9
* Version Independent ID: 2d7b250b-a699-f4bd-14f6-4496ec33cd42
* Content: [Schedule jobs to run automatically - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-job-queues-schedule-tasks)
* Content Source: [business-central/admin-job-queues-schedule-tasks.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-job-queues-schedule-tasks.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
No, we don't have an example ready for how to automate the job queue in code. But you can see examples of how to add background tasks here:[https://docs.microsoft.com/dynamics365/business-central/ui-batch-posting#to-set-up-background-posting-with-job-queues]( https://docs.microsoft.com/dynamics365/business-central/ui-batch-posting#to-set-up-background-posting-with-job-queues)
Since it would be a task to add code examples, I suggest that you submit a feature request here, using the Documentation catagory: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
