### ISSUE TITLE
reminder Terms

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#485]
[Enter feedback here]
Hello Can you please add some docs on Reminder Terms and interest rate accruals 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f0109b5-e9f8-5537-d13d-5f3c6f9cb8cf
* Version Independent ID: 669e2224-0f43-e744-d313-ff1d72d4fff2
* Content: [Set Up Payment Terms (IT) - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/localfunctionality/italy/how-to-set-up-payment-terms)
* Content Source: [business-central/LocalFunctionality/Italy/how-to-set-up-payment-terms.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Italy/how-to-set-up-payment-terms.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Good evening Ben,
It's a bit convoluted, but payment terms and reminder terms at set up in two different "systems", so to speak. So if you want to send reminders about overdue payments, then you set up levels of reminder terms (and you have to remember to run the job for sending reminders, of course). For example, you can add one or more reminder term levels where you choose the **Calculate Interest Rate** field and set the **Add. Fee. Calculation Type** field to **Accumulated Dynamic**, and then specify the rate in the **Additional Fee %** field (which you find in the **Additional Fee Setup** page).

Alternatively, you can create finance charge memos as described here: [https://docs.microsoft.com/en-US/dynamics365/business-central/receivables-collect-outstanding-balances](https://docs.microsoft.com/en-US/dynamics365/business-central/receivables-collect-outstanding-balances)

It's not convoluted by design - the intention is that each company choose the approach that works better for them. I'll add some links to make it clearer how things are tied together and work together in our next doc update.
