### ISSUE TITLE
Topic contains information pertaining to deprecated products

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-docs#498]
The following line contains information about deprecated features according to Deprecated Features in W1: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/deprecated-features-w1#:~:text=Changes%20in%202022%20release%20wave%201,-Web%20Service%20Access&text=The%20capability%20to%20access%20web,the%20authentication%20option%20for%20SaaS.

Business Central user accounts have web service access key.

According to the link, Web Service Access Keys must be replaced with OAuth authentication. 

1. Topic should contain a note about deprecation
2. Please provide some sample code for how to use OAuth authentication

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f0d4b2d-e2f5-a8bb-27bb-3a6975169dc0
* Version Independent ID: a23bba5a-ee49-8910-b84b-c23f479caec6
* Content: [Enabling Power BI Integration With Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-powerbi-setup#setup)
* Content Source: [business-central/admin-powerbi-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-powerbi-setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! We are aware that web service access keys will be deprecated next year. My colleague is working on updates to this content as part of our work on 2021 release wave 1. You'll see changes when we publish the docs for the April release.

I'm closing the Issue now because we have a statement about the deprecation in the article that you refer to, and we have notes in the administration content that encourage people to use OAuth instead of basic auth, such as this one: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/web-services-authentication
