### ISSUE TITLE
Make to order vs Make to Stock

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#523]
Under the manufacturing system there is the ability to plan based on MPS or MRP.

Can you please help share the value of the 2 options. This will be a detailed document and will help people understand made to order vs make to stock.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17cd2464-d864-faf7-2001-979ddf45fbd0
* Version Independent ID: 5813814a-8473-a434-8216-4f7461faed00
* Content: [Execute Production - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/production-manage-manufacturing)
* Content Source: [business-central/production-manage-manufacturing.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/production-manage-manufacturing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Thanks for the suggestion! We have a description posted here: https://docs.microsoft.com/en-us/dynamics365/business-central/production-how-to-run-mps-and-mrp

Does that answer your needs? If not, I'll add an entry to our backlog since it would require some resources that we don't have right now.

thanks!
