### ISSUE TITLE
Link the Developers learning catalog

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-docs#525]
In the **Developer** section, I am missing a link to https://docs.microsoft.com/en-us/dynamics365/business-central/readiness/readiness-learning-developers

I actually could not find the page that actually links to that useful article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1727c636-05cf-06e9-ef84-a0bb9ae53574
* Version Independent ID: 199c2d3d-2869-b4bc-e4e6-fdb9d60597c7
* Content: [Business Central Learning Catalog - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/readiness/readiness-learning-catalog)
* Content Source: [business-central/readiness/readiness-learning-catalog.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/readiness/readiness-learning-catalog.md)
* Service: **dynamics365-business-central**
* GitHub Login: @loreleishannonmsft
* Microsoft Alias: **margoc**

**Comment by edupont04** [comment]
Hello Natalie,

Thank you for your feedback! This may sound a bit weird, so please hang in there:

When we redesigned the main readiness learning catalog, I deleted the link to the original readiness learning catalog for developers. The problem is that some of those videos are vastly out of date, and the people who were supposed to maintain the list are no longer with Microsoft. So we got a lot of feedback about links being broken or targets being outdated without being able to do anything about it. But we hope that someone will again be able to maintain the catalog, which is why we didn't delete it.

My answer does not solve our shared problem, but we're adding a lot of learning modules to Microsoft Learn: https://docs.microsoft.com/en-us/learn/browse/?products=dynamics-business-central&roles=developer&resource_type=learning%20path
