### ISSUE TITLE
Dependencies in build pipelines

### ISSUE THREAD

**Issue by mabessghaier** [MicrosoftDocs/dynamics365smb-docs#528]
Hello, 

We're using a dependencies with free partner App in our extensions. I downloaded a latest available version 1.3.7723.3 for BC 17.5.  

The App compile correctly from vs code, however I get an error when using Freddy's script for  build pipeline, 

![image](https://user-images.githubusercontent.com/44379762/113870830-40944900-9780-11eb-835a-0f37fb1f21f7.png)

I added a secure url with the app file in the setting installApps as shown below 

![image](https://user-images.githubusercontent.com/44379762/113870889-51dd5580-9780-11eb-82f4-779017fcf4fe.png)

do you have any recommendations ? 

Thanks

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact the community and/or Freddy through the Dynamics 365 Business Central network in Yammer. 

Alternatively, if you suspect that something is wrong with the product, contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
