### ISSUE TITLE
Canada tax

### ISSUE THREAD

**Issue by KC-NAV** [MicrosoftDocs/dynamics365smb-docs#535]
I think this is incorrect, "In Canada, when you sell to a customer at a location where you do not have a situs—or a legal location in that province/state—you do not collect sales tax. "  Federal tax would be charged and collected.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37739b76-5dac-9cdb-58e8-6f5163cf63ec
* Version Independent ID: ee20609f-a747-ce9b-152f-b4d7767db8ad
* Content: [Setting Up Tax Groups, Areas, and Jurisdictions in Canada - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/localfunctionality/canada/ca-sales-tax)
* Content Source: [business-central/LocalFunctionality/Canada/ca-sales-tax.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Canada/ca-sales-tax.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! I'll get this confirmed on our side and then the question clarified in a doc update.

**Comment by edupont04** [comment]
Hello @KC-NAV,

Sorry for the delay in getting back to you, but as far as I can tell, you're right. This confusing statement will be removed in the next doc update - it was added originally due to confusion around the way that Dynamics 365 Business Central works in North America and was supposed to apply to the US only.
