### ISSUE TITLE
Routing Link Code

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#537]
Can we please get an update on the Routing Linking Code and how this benefits manufacturing?
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 116dcd57-f002-5963-71e6-da6db354ec07
* Version Independent ID: 50141a0e-bc99-4f41-8838-e17611181f76
* Content: [How to Create Production BOMs - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/production-how-to-create-production-boms)
* Content Source: [business-central/production-how-to-create-production-boms.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/production-how-to-create-production-boms.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! As explained in the article that is linked to from this one, you can create routing links to connect components to specific operations in order to retain their relationship even though the production BOM or routing is modified. For more information, see https://docs.microsoft.com/en-au/dynamics365/business-central/production-how-to-create-routings#to-create-routing-links

**Comment by edupont04** [comment]
Answered.
