### ISSUE TITLE
Misleading

### ISSUE THREAD

**Issue by kelseykoep** [MicrosoftDocs/dynamics365smb-docs#54]
This document is Misleading. In the beginning you say BC can present itself in multiple languages, but then in the purple box below you say it's not supported? From my understanding, you cannot change languages. So if I deploy an France instance, I cannot change the language to English. What is correct? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71861b3-1f71-62fa-9cff-c49138d9b1fb
* Version Independent ID: 560d0c1c-41db-e23c-5ad6-66591b493277
* Content: [Multilanguage and Localization - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/about-locale-language#feedback)
* Content Source: [business-central/about-locale-language.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/about-locale-language.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Kelseykoep,

Thanks for reaching out to us about this! You are right that the content is misleading. In fact, you *can* change the language, depending on your country/region. In your example, the French version of Business Central includes two languages by default, French (France) and English (United States), and each user can change the user interface language to either of the two languages. This is done in the My Settings window.

I will remove the confusing note.

**Comment by edupont04** [comment]
The fix is ready and will be available online within a week.

**Comment by kelseykoep** [comment]
Thanks for the reply Eva!

**Comment by edupont04** [comment]
My pleasure - sorry for the delay, though!

**Comment by PaddyPOwer123** [comment]
Hi Eva,
Is this the case for the Italian Language pack? This is good news we are about to implement a system in France and have English speakers in France.

**Comment by PaddyPOwer123** [comment]
Hi Eva, sorry to chase regarding Italy but we have a client who will only commit to this project if they can see BC in Italian and English. Otherwise they have said they will go with NetSuite which does work with multiple languages. Really disappointing MS has removed this very important feature from BC. It works on premise which from my perspective makes things worse. We are meant to be pushing cloud environments.

**Comment by edupont04** [comment]
Hi PaddyPOwer123,
In Business Central, language and functionality are closely related as described in this Help article. In Business Central online, the languages that users can see the user interface in is determined by the official languages of the country that the Business Central tenant is created in. For Business Central on-premises, there is an option of applying additional languages, but the required language packs are still work in process, I have been told.
Of course we want you to win this customer for Business Central, but unfortunately the people who might have further information about coming features are on vacation this week due to Danish holidays.
If you want to, you can vote for the suggestion to support multiple languages independent of local functionality here: https://experience.dynamics.com/ideas/idea/?ideaid=4af8fffa-9345-e911-867a-0003ff689b02
Also, if you want to, you can vote for the suggestion to allow multiple localizations here: https://experience.dynamics.com/ideas/idea/?ideaid=fc1a25e3-68e6-e811-a140-0003ff68b41e

**Comment by edupont04** [comment]
Just to clarify for everyone: In all versions of Business Central online, users can switch to the English (US) base language as well as the official language or languages of their country or region.
