### ISSUE TITLE
Doesn't work as of V191

### ISSUE THREAD

**Issue by idealsceneprod** [MicrosoftDocs/dynamics365smb-docs#57]
I'm logged in as delegated admin for a customer, and trying to lock down personalization for a single user. This functionality is not active. The buttons are all there, but only the View button is activated. I can copy a profile but can't modify the new profile. Can't even delete it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37666f25-436e-c4c9-2101-ac7eb2d482a3
* Version Independent ID: cfd398f5-97fd-44f9-2ae7-acf4627ce9d8
* Content: [Managing Personalization as an Administrator in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-personalization-manage)
* Content Source: [business-central/ui-personalization-manage.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-personalization-manage.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
I'm sorry to hear that you can't get the personalization to work for you. Please submit a product bug through normal channels and/or on the Ideas site at https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1
Closing the issue since it's about the product, not the docs.
