### ISSUE TITLE
Can't import encryption key for Saas version

### ISSUE THREAD

**Issue by MakerX101** [MicrosoftDocs/dynamics365smb-docs#589]
Encryption is always turned on for online versions, and you cannot turn it off.
But why i can't import encryption key for Saas version

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 677649e2-d481-3988-b615-fa3614e1603f
* Version Independent ID: d83f6d23-2c3e-1bb2-ddad-409ceaab58a4
* Content: [Manage Data Encryption - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/admin-manage-data-encryption)
* Content Source: [business-central/admin-manage-data-encryption.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-manage-data-encryption.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello @MakerX101, 
Thank you for your feedback! As explained in the administration content, you cannot import or export encryption keys for Business Central online: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-encrypting-data

Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
