### ISSUE TITLE
Cannot Find the XMLPort 10860 in the french localization

### ISSUE THREAD

**Issue by Steven-Bale** [MicrosoftDocs/dynamics365smb-docs#590]
Hello,

thanks for the documentation but i cannot find the XML port 10860 ETEBAC in V18 of Business Central Online.

Where can i find it or what program replace it ?

Thanks.
Steven.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: bfe3019f-6173-beaf-a608-83a5b0b48edc
* Version Independent ID: 59cad8fa-cc36-6965-f69d-cd7746c4836b
* Content: [Procédure d'exportation ou d'importation des paramètres de configuration de la gestion des paiements - Business Central](https://docs.microsoft.com/fr-fr/dynamics365/business-central/localfunctionality/france/how-to-export-or-import-payment-management-setup-parameters)
* Content Source: [business-central/LocalFunctionality/France/how-to-export-or-import-payment-management-setup-parameters.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/France/how-to-export-or-import-payment-management-setup-parameters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Steven,

Thank you for your feedback! I'm investigating what has happened to the XMLports and will update this thread and the relevant documentation once I find out.

**Comment by edupont04** [comment]
Hello again,

Once again, thank you for your feedback! The confusion is caused by a mistake, in that we forgot to update this article when we added support for SEPA credit transfers and SEPA direct debet a long time ago. Those three XmlPorts are long gone, and instead you have to create the relevant payments steps,set the Action Type field to File, and then specify the type of file in the Export Type field. For SEPA Credit Transfer files, specify XMLport, and then set the Export No. field to 1000.For SEPA Direct Debit files, specify XMLport, and then set the Export No. field to 1010.

We'll clarify this in our next doc update, probably Thursday this week (July 8, 2021).

**Comment by edupont04** [comment]
This is now updated in English: https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/france/how-to-set-up-payment-classes

Translation into French will be available in 3 weeks.

**Comment by Steven-Bale** [comment]
Hello,

I tried the steps described above and i have the following error message ; 
Le XmlPort SEPA DD pain.008.001.02 ne contient pas de XmlItem qui utilise la table (Table 10865 Payment Header) spécifiée dans la fonction SetTableView.

I think this XMLPort is not compatible with the payment slip functionality.
Thanks.
Steven
