### ISSUE TITLE
Separate out Requisions Worksheet

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#598]
I was looking through the list of functions and Requisition Worksheet is a little hidden in Planning worksheets and requisition worksheets Can you make this a topic on the left more visible?

The question I was looking for was whether or not SKU is required for requisition worksheet to pick up the max order qty. Or is SKU only required when Premium experience is enabled.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3e2d1-8867-002b-c5c0-5492417adea4
* Version Independent ID: 635ff905-4ff7-49b2-df5a-cdb1143dcae8
* Content: [About Planning Functionality - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/production-about-planning-functionality#requisition-worksheet)
* Content Source: [business-central/production-about-planning-functionality.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/production-about-planning-functionality.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! It's a good suggestion, so we'll get the requisition worksheet mentioned in the table of contents on the left fixed in the next doc update.

As for how the requisition worksheet works across license types, I'm not the expert. The requisition worksheet can be used even with the Essential license. But if you want to use it with more advance production planning functionality, you'll need the Premium license.

As I understand it, the requisition worksheet will pick up the Maximum Order Quantity field from the relevant item or SKU, but the planning engine is part of the Premium license.

**Comment by makdaddy8888** [comment]
Hi Eva

Inventory setup and the locations check box enables this function. Can you please get the docs updated with this information too?
Maybe speak to a functional consultant to confirm?

Kind Regards
Ben Opit
+61411707070

**Comment by edupont04** [comment]
Hello Ben,

It's kind of explained here: https://docs.microsoft.com/en-us/dynamics365/business-central/production-planning-with-without-locations
I agree with you that the information is scattered, and I'll see what we can do about that.

**Comment by edupont04** [comment]
Now live with more details on the confusing fields.

**Comment by makdaddy8888** [comment]
:) thanks Eva

Kind Regards
Ben Opit
+61411707070

**Comment by makdaddy8888** [comment]
Hi Eva

Can you add my GitHub account on that page to indicate that public citizen’s are providing positive feedback which as a community is helping all Business Central users around the world. I am always telling people that Microsoft do listen. 

Kind Regards
Ben Opit
+61411707070

**Comment by edupont04** [comment]
Hi Ben,

We do listen, though we can sometimes be slow at reacting to feedback for various reasons. 

However, the way it works with accounts shown as contributors to a given article on docs.microsoft.com is somewhat convoluted. For example, this article was heavily edited by an external contributor, but his account is not attributed, while someone inside Microsoft did some tweaks and their account _is_ attributed: 
[https://docs.microsoft.com/en-us/dynamics365/business-central/across-use-workflows](https://docs.microsoft.com/en-us/dynamics365/business-central/across-use-workflows)

This is because we publish from our internal repo rather than this public repo. And information about the external contributor sometimes gets lost in the publishing system. Sometimes, but not always, which makes it even more confusing.

All contributions are greatly appreciated, both external and internal.
