### ISSUE TITLE
Fonts not working for reports

### ISSUE THREAD

**Issue by kristapsxv** [MicrosoftDocs/dynamics365smb-docs#600]
Changing to report fonts to business central allowed fonts does not work. the font stays the same.
Is it possible to change the font for reports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 082b762b-f7b9-3d50-af8a-c892b34f6347
* Version Independent ID: 3170ce53-ed8e-da6c-7a9f-bf5d6d31e20a
* Content: [Available Fonts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-fonts)
* Content Source: [business-central/ui-fonts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-fonts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. As this article explains, you can change between specific fonts in Business Central. If you find that this capability is not working for you, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).

You can read about changing reports here: https://docs.microsoft.com/dynamics365/business-central/ui-manage-report-layouts

I hope this answers your questions; otherwise do let us know!
