### ISSUE TITLE
Opening Balances Best Practices

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#616]
Can you please help share when opening balances are being created what fields are mandatory and which a desirable to fill in?

I ask this as when you create a config package (for AR opening balance for example) you end up getting many rows of data to be populated and it would be good to get some official guidance from MS on what fields should be filled in including weather a negative value should be used. Eg AP opening balances.

This page is detailed but no guidance is offered around best practices.
Thank you
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 168537d4-aab5-bc33-24f3-2808d30478ac
* Version Independent ID: f568493d-e549-f834-3385-ddf5db8f44c1
* Content: [Migrate Customer Data - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-migrate-customer-data)
* Content Source: [business-central/admin-migrate-customer-data.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-migrate-customer-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! When you work with data in Excel, you can't tell which fields are required. But you can see that in the equivalent page in Business Central. For example, on the G/L Account Card page, you can see that only the No. field is required, though obviously it would only make sense if you also specified a name and whether the account must be used for the income statement or the balance sheet, and so on.

In general, we do not provide best practices for how to define general ledger accounts, or how to design your chart of accounts. This is because best practices depend on many factors, including industry, location, and, in some cases, personal habits or preferences of the accountant. So I'm closing this feedback entry as a Won't Fix.
