### ISSUE TITLE
customer price group hierarchy 

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#619]
What is the hierarchy of pricing group?

For example
Parent Price First
Child Price Second?

Here is the Sales Type Filter
1. Customer
2. Customer Price Group
3. All Customers
4. Campaign
5. None

The issue we have is that we are using a different bill-to another customer account and the parent pricing is being defaulted.

Can this section please get updated to reflect the precedence order?

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d20592c1-805e-cb34-1f1a-d2f5f6b056a4
* Version Independent ID: a8f2d0d7-a3ba-7994-2b09-e3a0b08afbd3
* Content: [Set Up Special Sales Prices and Discounts for Customers - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/sales-how-record-sales-price-discount-payment-agreements?tabs=current-experience)
* Content Source: [business-central/sales-how-record-sales-price-discount-payment-agreements.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-how-record-sales-price-discount-payment-agreements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! You're right that we don't say much about customer price groups and how the defined sales prices are then calculated. I have added a work item to our backlog to get this sorted in a future update.

In answer to your immediate questions, the Bill-To Customer field plays a role in the price calculation, because it's that customer's Customer Card information that is used. At least, that's how I understand things. But when our team picks up this work item, we'll get help from someone who knows more about this than I do.  

There is a tiny hint of how this works in the field Help for the Bill-To Customer field for Dynamics NAV 2016 here: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh895161(v=nav.90)
A quote: All customer-related information regarding invoicing, discounts, statistics, dimensions, and so on, will refer to the customer who receives the invoice, not the customer who receives the items.
