### ISSUE TITLE
Managing Back Orders

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#642]
Hi Eva

Not sure if I have asked for this to be documented but there seems to be no way of managing open orders that are partically delivered. Do you have some specfic processes you can share on this help page?
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e6d3e01-3bde-4117-5851-2578b1b24158
* Version Independent ID: 732a8fbf-673d-1487-973b-cb2079bd4e08
* Content: [Overview of Tasks to Manage Sales - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/sales-manage-sales)
* Content Source: [business-central/sales-manage-sales.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-manage-sales.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,

Thank you for your feedback, but it's one of those things that depend very much on how your organization works. Business Central itself doesn't have specific reports that you can run to identify open sales orders with partial shipments, but you can set a filter on the Sales Orders page for the Completely Shipped field being set to No, for example. That would then show you the list of open orders with partial shipments. Then you can process the open orders in any way that you want.

We hint at the capability in step 12 here: https://docs.microsoft.com/dynamics365/business-central/sales-how-sell-products

I hope this answers your question. Otherwise, do let us know.
