### ISSUE TITLE
Item Tracking in the Warehouse

### ISSUE THREAD

**Issue by njackson1582** [MicrosoftDocs/dynamics365smb-docs#645]
The page referenced below is seemingly in contradiction with the procedures outlined in [this blog post](https://thatnavguy.wordpress.com/2021/10/13/checking-lot-numbers-in-bin-content/). If you enable "Lot Warehouse Tracking" or "SN Warehouse Tracking" you will get lot/serial numbers on your Warehouse Entries, not just your Item Ledger Entries. 

However, the article states "reservations and item tracking numbers can be handled only at the location level, not at the bin and zone level" which seems to be inaccurate. I also very well could be misreading the article. 

Could someone provide details on what the article is detailing, specifically around capabilities of item tracking in the warehouse?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a6ed02f-8213-5b88-e4c1-c548917a30e7
* Version Independent ID: 16451d77-895b-d23b-0732-800449b83e62
* Content: [Design Details - Item Tracking in the Warehouse - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-item-tracking-in-the-warehouse)
* Content Source: [business-central/design-details-item-tracking-in-the-warehouse.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/design-details-item-tracking-in-the-warehouse.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

The article is correct. It provides details on how to track serial and lot numbers at warehouse level. The item tracking engine, which is build on top of the reservation engine, does not support tracking at the bin level. For information about that, see [Design Details: Item Tracking Design](https://docs.microsoft.com/dynamics365/business-central/design-details-item-tracking-design).

Therefore, in addition to the standard item tracking engine, we use an additional engine for warehousing. It's integrated with standard engine in a way that's similar to how warehouse entries integrate with inventory. For more information, see [Design Details: Integration with Inventory](https://docs.microsoft.com/dynamics365/business-central/design-details-integration-with-inventory)

However there is no additional reservation engine, which is why there are some nuances when dealing with reservation of specific serial and lot numbers, as well as availability calculations. For descriptions of those nuances, see [Design Details: Availability in the Warehouse](https://docs.microsoft.com/dynamics365/business-central/design-details-availability-in-the-warehouse).
