### ISSUE TITLE
app installation / naming of the "menu icons"

### ISSUE THREAD

**Issue by wic365** [MicrosoftDocs/dynamics365smb-docs#647]
If you do this and you have multiple tenant, (multiplpe companies), the installation is called "production" but you don't know from which tenant we are talking. Should be possible to rename the desktop icon. 
BR, Chris
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94391efb-4cb1-5b61-6950-b50a9597bd5a
* Version Independent ID: bd8e819f-132a-86ce-83f7-b1bc291287a8
* Content: [Get Business Central on Your Desktop - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/install-desktop-app)
* Content Source: [business-central/install-desktop-app.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/install-desktop-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! However, as I assume you know from all other apps, you can't rename them once they're installed. You can choose to take the suggestion in the second bullet under step 2 in Install the app: "Don't select the environment, and just go to next step to install the app. In this case, the installed app will open the environment selection page, instead of a specific environment." 
Alternatively, you can use Edge for one environment and Chrome for another, our you can move the desktop shortcuts to specific subfolders to reflect the environments that they are for.

Finally, since your question is not really about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
