### ISSUE TITLE
Page has mixed description between GST and VAT

### ISSUE THREAD

**Issue by ScwB** [MicrosoftDocs/dynamics365smb-docs#658]
It looks like this GST page was a modified copy of a VAT page, and it has errors. It bounces back and forth between GST and VAT, and is confusing.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 131fb416-2e6f-dee8-5b22-b8ba1f95c7f5
* Version Independent ID: 65cc2377-940c-ad01-9ddd-0ccf47c12562
* Content: [Set Up Sales Tax - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/finance-setup-vat)
* Content Source: [business-central/finance-setup-vat.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/finance-setup-vat.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! You're quite right that something has gone wrong in the English (CA) version of this article. Because, as you point out, Canada uses GST/HST, which we talk about in the Canadian section here: https://docs.microsoft.com/dynamics365/business-central/localfunctionality/canada/sales-tax-goods-services

I'll ask our translation team to update the article for the base version so that this will be fixed in the next doc update for your language. However, in Canada, it is more correct to use the batch job that I think is still called "GST/HST Internet File Transfer" to generate the .tax files.

**Comment by edupont04** [comment]
Fixed in the December translations: https://docs.microsoft.com/en-ca/dynamics365/business-central/finance-setup-vat

**Comment by edupont04** [comment]
Oops., no, it will be fixed in the January translations. Reopening.

**Comment by edupont04** [comment]
Now live.
