### ISSUE TITLE
Layout Belgisch ondernemingsnummer

### ISSUE THREAD

**Issue by MarcVranken3120** [MicrosoftDocs/dynamics365smb-docs#659]
[Voer hier feedback in]
Hi,
what is the exact format for the Belgian Enterprise number in the upload file with Rapidstart?
And what is the correlation with Region code (BE)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 3cb65bc2-6aa7-a2f1-b725-b23d7aa27152
* Version Independent ID: 77c76883-0bbf-ffac-a7ab-2e976d911b53
* Content: [Ondernemingnummers en filiaalnummers \[BE\] - Business Central](https://docs.microsoft.com/nl-be/dynamics365/business-central/localfunctionality/belgium/enterprise-numbers-and-branch-numbers)
* Content Source: [business-central/LocalFunctionality/Belgium/enterprise-numbers-and-branch-numbers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Belgium/enterprise-numbers-and-branch-numbers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Since your question is not about the Help for Dynamics 365 Business Central, we suggest that you ask the community at https://community.dynamics.com/business/f/dynamics-365-business-central-forum.

However, I will make sure we add the link to the https://kruispuntdatabank.be/ website where company numbers are defined in Belgium.
