### ISSUE TITLE
Alternate Work Centre

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#696]
some more details on this option would be great. How dioes this function help or add the to process?
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690eac98-0b6d-2a82-6cd4-7e0ab849ba34
* Version Independent ID: d6f47217-042a-ca86-87f0-dede1c9a3606
* Content: [Set Up Work Centres and Machine Centres - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/production-how-to-set-up-work-and-machine-centers)
* Content Source: [business-central/production-how-to-set-up-work-and-machine-centers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/production-how-to-set-up-work-and-machine-centers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

The alternate work center setting is for information only, and isn't actually used by any processes. It's just to let production planners know which work center to use if the primary work center isn't available for some reason. I've added a small mention of that in step 5 of the "To set up a work center" procedure in the article, and we'll publish the updated soon.

I've also added a task to our backlog to improve the tooltip for the Alternate Work Center field. That should also help clarify its purpose. Tooltips live in the code though, so that fix won't be available until the next minor update.

Thanks for bringing this up.
