### ISSUE TITLE
[de-DE] Search Results

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#71]
The internal Search shown me result pages which did not contain the search string "Kontenplan": https://docs.microsoft.com/de-de/search/index?search=Kontenplan&scope=BusinessCentral -> 287 Results

E.g. the result pages 3. https://docs.microsoft.com/de-de/dynamics365/business-central/warehouse-how-to-plan-warehouse-movements-in-worksheets, 4. https://docs.microsoft.com/de-de/dynamics365/business-central/warehouse-how-to-plan-put-aways-in-worksheets and 5. https://docs.microsoft.com/de-de/dynamics365/business-central/production-how-to-plan-project-orders does not contain the search string "Kontenplan".

In comparison: https://www.google.de/search?q=Kontenplan%20site:https://docs.microsoft.com/de-de/dynamics365/business-central/ -> 42 Results

**Comment by edupont04** [comment]
Hi Daniel,

Thanks for reporting this! I'll send the information to the team who own the Search functionality.

**Comment by DanielGoehler** [comment]
Hi @edupont04, still no changed. It looks like that the Search splits "Kontenplan" into "Konten" and "plan" and lists [Vorgehensweise: **Plan**en von Lagerplatzumlagerungen in Vorschlägen](https://docs.microsoft.com/de-de/dynamics365/business-central/warehouse-how-to-plan-warehouse-movements-in-worksheets), [Vorgehensweise: **Plan**en von Einlagerungen in Vorschlägen](https://docs.microsoft.com/de-de/dynamics365/business-central/warehouse-how-to-plan-put-aways-in-worksheets), [Auftrag nach Auftrag **plan**en](https://docs.microsoft.com/de-de/dynamics365/business-central/production-how-to-plan-for-new-demand), [Projekt nach Projekt **plan**en](https://docs.microsoft.com/de-de/dynamics365/business-central/production-how-to-plan-project-orders).

**Comment by edupont04** [comment]
Hi Daniel,

Well, at least the first search result is now [Einrichten eines Kontenplans - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/finance-setup-chart-accounts), so that's an improvement.

I know that the team that owns the Seach functionality on the Docs site have tweaked their algorithms multiple times, and it looks like an important language such as German is not necessarily getting the attention it deserves. I'll let them know.
