### ISSUE TITLE
Please provide documentation

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-docs#72]
I count 21 editable parameters/settings on the Job Queue Entry Card. 14 if you don't count the "Run on &lt;day of week." checkboxes.  
I count 0 named parameters that are identified or explained on this documentation page. I am a user/developer, and I need to know the implication and use of the "Maximum No. of Attempts to Run" parameter, so I can implement it properly. If there is to be documentation, please provide it down to the level of editable parameters, so that users can know how to properly configure their systems.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fcb95cd-fd17-03c1-d52b-368c37671df9
* Version Independent ID: 2d7b250b-a699-f4bd-14f6-4496ec33cd42
* Content: [Schedule jobs to run automatically - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-job-queues-schedule-tasks)
* Content Source: [business-central/admin-job-queues-schedule-tasks.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-job-queues-schedule-tasks.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello buzzwick,

Thank you for your feedback! In Business Central, the explanation of each field in a given page is implemented as a tooltip, so that you can find out what the field does right there in the product. That is why you rarely find descriptions of fields in the docs.
To read a tooltip, either hover over the name of a field, or choose the name of the field. Specifically for the Max No. of Attempts to Run field, this is the description: 
"Specifies how many times a job queue task should be rerun after a job queue fails to run. This is useful for situations in which a task might be unresponsive. For example, a task might be unresponsive because it depends on an external resource that is not always available."

**Comment by buzzwick** [comment]
Aha! Wonderful! Okay, this is very helpful because I will stop looking in the wrong places.

One feature request:  Someone decided that a Tool Tip should disappear just before it has been visible long enough to read these helpful messages. Is there a way to lengthen that setting, or to keep Tool Tips in place until the cursor is moved off the field?

Thanks again,

David

**Comment by edupont04** [comment]
Hi David,

I'm happy to help - tooltips are a bit problematic, I agree, but that's the implementation we have currently. One of the problems is that you can only view the tooltip if you use a mouse device or a touch screen, not if you navigate Business Central using a keyboard.

Anyway, here is how to keep a tooltip open long enough to actually read it:
In a page like the Customer Card, simply choose the name of the field. That leaves the tooltip open until you leave the field again.
In a list such as the Customers list, or the lines in a document such as a sales order, you have to choose the little drop-down menu to the right of the name of the column and then choose the "What's this?" menu item.

I'm going to add these tips to the Help so that other people also get the benefit of our tooltips.

**Comment by edupont04** [comment]
Hi David,

With your mouse, click the name of the field. That opens the tooltip and leves it open until you move on to another field on that page.

**Comment by buzzwick** [comment]
Nope, sorry, that is not what I am seeing. This is NAV 2018. Clicking on the field does nothing if the tool tip is not visible and makes it go away if it is.  Are you seeing this behavior in a version you are running?

**Comment by buzzwick** [comment]
Eva,
Not a problem at all. I get it. We are testing with Dynamics 365 now, so going forward we will have the benefit of that functionality. It's good to hear that someone picked this up in the transition from NAV to 365.
Thanks so much for your responsiveness!
