### ISSUE TITLE
Explanation of Contact Ratings mentioned in the setup of questionnaire's

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#729]
Hello Eva.

This page states.:

"After you have created a questionnaire, you must create contact ratings to classify your contacts."

If I do a search in BC, there is no relevant option returned for "Contact Rating" or "Contact Classification".  The documentation leads you to believe there is a specific step "AFTER" creation of the questionnaire to set up 'contact ratings'.  Can you put a link into the documentation to this process as BC itself doesn't return any results.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 291e58ff-5c30-6a3c-57af-519ab182aa7d
* Version Independent ID: 13867b23-98d8-af82-53c0-8b51c41873a6
* Content: [Use profiles to classify contacts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-create-contact-profile-questionnaire)
* Content Source: [business-central/marketing-create-contact-profile-questionnaire.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/marketing-create-contact-profile-questionnaire.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Chris,
Thank you for your feedback! This article is a patchwork of content from an older version of our docs, and I admit that it's not so easy to understand (but then you should see the original, which is even harder to read, in my opinion).  The message that the article is trying to push is that you can set up questionnaires that can help you "rate" your contacts so that your campaigns hit the right people. Its kind of hinted at in the "The Automatic Classification of Contacts" section. I'll try to make this clearer in the next doc update.
