### ISSUE TITLE
Copy / Export Data to Sandbox

### ISSUE THREAD

**Issue by Mr-Pingu** [MicrosoftDocs/dynamics365smb-docs#73]
I can't seem to find a way to copy all my settings & added data (eg products, vendors and customers) to the sandbox so I can test in a much more replicated environment. Is this there a way to export a whole company for back-up purposes or to export it to the sandbox environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d60d56-bfba-902b-9c10-87bbc3ad72d1
* Version Independent ID: 9be1af8c-eeca-c96f-330d-6c08ac03436a
* Content: [How to Copy Data to New Companies - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-to-copy-data-to-new-companies)
* Content Source: [business-central/admin-how-to-copy-data-to-new-companies.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-to-copy-data-to-new-companies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello Mr-Pingu,

Thank you for your feedback!  You can create a sandbox environment with production data using the preview Sandbox Environment wizard. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-create-sandbox-environment.

Alternatively, if you are a Business Central partner, or you have an agreement with a Business Central partner that has access to the administration center for your Business Central tenant, you can create a sandbox environment with production data in the tenant administration center. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center

I hope this answers your question. Otherwise, please let us know.

**Comment by Mr-Pingu** [comment]
Hello edupont04,

For the first method, this doesn't transfer all my companies to the sandbox. When I create or reset the sandbox I don't get all the companies and the data from these companies. 

For the second method. I passed it to my Business Central Partner and will get back to you when I have more information on this specific matter.
