### ISSUE TITLE
bussiness central cloud can not searh General ledger setup

### ISSUE THREAD

**Issue by eat110** [MicrosoftDocs/dynamics365smb-docs#741]
I found out that I can't search General ledger setup in bussiness central cloud search box Last week. 
It was work well before
Anyone know how to solve it or what is the reason?
 
![1652699355(1)](https://user-images.githubusercontent.com/28883324/168580248-908adfcf-774e-4ec7-81db-7e8aae0fb3fb.png)

**Comment by edupont04** [comment]
Hello, thank you for your feedback; however, since it's not about the documentation, you might want to ask your question in the community at https://community.dynamics.com/business

However, this morning, the in-product Search found the General Ledger Setup page just fine for me in my US tenant, so maybe you were running Business Central in another language at the time?
