### ISSUE TITLE
Outdated page. (Create Users According to Licenses)

### ISSUE THREAD

**Issue by Joseph-Candava** [MicrosoftDocs/dynamics365smb-docs#757]
I took a look at this documentation page where it has told me to go to Users, then Related, then within that menu, I do not see the mentioned "Update Users from Microsoft 365" option. Can this page be updated to suit this version of Business Central?
(19.3.34541.35247) Related Documentation: https://docs.microsoft.com/en-au/dynamics365/business-central/ui-how-users-permissions#adduser

<img width="955" alt="image" src="https://user-images.githubusercontent.com/9446000/173002690-f015507f-98c0-4db4-8640-88e5bc7a48d0.png">

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af56319-74d0-ce95-7f11-48a0b165ed6e
* Version Independent ID: d496d459-af33-c965-a21b-0e2f44d6a2e9
* Content: [Create Users According to Licences - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/ui-how-users-permissions#adduser)
* Content Source: [business-central/ui-how-users-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-how-users-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! In our content, we often use the phrase "Choose the Lightbulb that opens the Tell Me feature. icon, enter <name of a page>, and then choose the related link." because it's the easiest way to get to a page/list/card, no matter how many personalisations a user might have made.
 We also often don't say exactly where on the page a specific action or button is located, again due to personalisation and other changes to the look and feel of the product.

In this particular case, the section that you refer to does not tell you that the **Update users from Microsoft 365** action is located in the **Related** menu. The words are as follows:

1. Choose the <lightbulb> icon, enter Users, and then choose the related link.
2. Choose Update Users from Microsoft 365.
 
In the default version of Business Central, the action is found under the **Process** menu, but in your environment, it might be somewhere else.

I hope this helps. otherwise, do let us know.

**Comment by Joseph-Candava** [comment]
I was able to find the Update Users from Microsoft 365 by clicking on the magnifying glass icon and typing the function up there.
Thank you for your help.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/9446000/173008426-26621efa-c475-44ef-bb69-5f58f01140a5.png">
