### ISSUE TITLE
cannot create user in demo trial without real 365 admin access 

### ISSUE THREAD

**Issue by cnguy01** [MicrosoftDocs/dynamics365smb-docs#783]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee3de901-2ce9-aa4c-2161-a2f2ee9b163b
* Version Independent ID: ac8d678c-f006-2425-fd82-3b7f44c037b0
* Content: [Setting Up and Using a Purchase Approval Workflow - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/walkthrough-setting-up-and-using-a-purchase-approval-workflow#feedback)
* Content Source: [business-central/walkthrough-setting-up-and-using-a-purchase-approval-workflow.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/walkthrough-setting-up-and-using-a-purchase-approval-workflow.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
This article is meant to help people get to understand the approval workflow capability both in a production environment and in a trial environment. But you are right that in a trial environment you cannot import users from Microsoft 365 because no licenses have been applied yet. Instead, you can create a local user, I believe. But as you can see, the walkthrough expects you to be a superuser who signs in as two different users, so I wouldn't recommend you to follow these steps if you're still in a trial environment and not yet ready to onboard with Dynamics 365 Business Central.
