### ISSUE TITLE
Business central table of contents renders in navigation

### ISSUE THREAD

**Issue by elliottjb7** [MicrosoftDocs/dynamics365smb-docs#79]
After pulling the main branch and running docfx in /business-central, the structure of the folder (ie md files in 'parent' folder) means the toc is rendered as part of the navigation. If the md files are relocated to a subfolder, the toc displays as expected when under /subfolder-url. Is this an error or am I using files in the wrong way? Thanks!

**Comment by edupont04** [comment]
Hi elliottjb, and my apologies for not catching this sooner due to the holidays!

The TOC is a manual process to maintain. Links to .md files in subfolders have to be written out with the relative path as in "### [Set Up Delivery Reminders](LocalFunctionality/Austria/how-to-set-up-delivery-reminders.md)".

So if you move a file to a subfolder, then you have to update toc.md (and toc.xml if you use Help Server) accordingly.

You'll also notice that we use the toc.md file to group content in a way that doesn't reflect the underlying folder structure - this is a side effect of the fact that the toc.md isn't automatically generated and gives us great flexibility in associating content across folders.

I hope this answers your questions. Otherwise do let me know!
