### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Stefan-Bar** [MicrosoftDocs/dynamics365smb-docs#795]
Ist 
Bestelldatum + Beschaffungszeit + Eingeh. Lagerdurchlaufzeit + Beschaffungszeit 
wirklich das 
Erwartetes Wareneingangsdatum,
wie angegeben?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0b4f3fd5-03e2-c8c6-9a05-23ce8893b834
* Version Independent ID: 95b969fb-97c9-9d9d-2a69-9f692683a585
* Content: [Daten für Einkäufe berechnen - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/purchasing-date-calculation-for-purchases)
* Content Source: [business-central/purchasing-date-calculation-for-purchases.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/purchasing-date-calculation-for-purchases.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. My apologies for answering you in English, but I suspect that you might have misread the wording.
The article says that expected receipt date (Erwartetes Wareneingangsdatum) is based on the planned receipt date (Geplantes Wareneingangsdatum), the inbound warehouse handling time (Eingeh. Lagerdurchlaufzeit), and the safety lead time (Beschaffungszeit). The bullet ahead of that text says that the planned receipt date is based on the order date and the lead time calculation.

I hope this answers your question. otherwise, do let us know.

**Comment by Stefan-Bar** [comment]
Sorry, you do not see the point.
![image](https://user-images.githubusercontent.com/82201382/191923039-a24b1d84-0262-4589-b150-72e522f28136.png)
If you put the first equation into the second, you end up with 2 x "Bestelldatum", which does not seem correct.
