### ISSUE TITLE
Documentation Tagging

### ISSUE THREAD

**Issue by BradKCox** [MicrosoftDocs/dynamics365smb-docs#80]
Hi, 

After taking some time to work through some of your training docs as a Nav partner we feel that additional tagging would benefit new users with differing language. 

For an example if a new user is looking to set-up a new chart of accounts code they may search for Nominal code and would receive nothing back from the search in either SaaS Nav or directly in the search bar on this portal. I believe this would give users a better experience in learning the Nav naming scheme vs what they are familiar with.

Many Thanks
Brad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b86d301-cf03-0dd0-abdd-9a73743b4285
* Version Independent ID: 4e4d4219-2c2f-0324-6166-414f31158224
* Content: [Meet Microsoft Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/index#feedback)
* Content Source: [business-central/index.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/index.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hi Brad,

Thank you for your feedback! Due to the holidays, we didn't catch your suggestion until now, but you're touching on a subject that we're already working on. 

We're making incremental updates to the metadata for the most relevant Help articles as we learn about different terminology. This metadata is used by the in-product search and by the search functionality on the Docs.microsoft.com site. We're not claiming victory yet, obviously, because it is a monumental task to get all synonyms across the breadth of the business application areas. But again, thank you for your suggestion!
