### ISSUE TITLE
Open Company ...

### ISSUE THREAD

**Issue by pvreugdenhil** [MicrosoftDocs/dynamics365smb-docs#802]
[Enter feedback here]
I would love to see again in BC a quicker option to "Open a company". In NAV the short-cut CTRL+O was available and pressing in every screen on the company name at the lower left corner. Now to change company the only route is via my settings. As I have more then 35 companies now in a single environment I would love to reappear a customization to get this "open" company via a short-cut.  This is a small item any not to compare to the very great benefits and improvements to be able to work with BC. 
I might someone can redirect this to a place where it could be taken care of. 

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc9174f7-cad5-7550-b93b-036158d40e38
* Version Independent ID: 8e4dabaa-c112-6a2e-dc18-933253579927
* Content: [Personalising Pages (contains video) - Business Central](https://learn.microsoft.com/en-gb/dynamics365/business-central/ui-personalization-user#Actions)
* Content Source: [business-central/ui-personalization-user.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-personalization-user.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Thanks for the asking. Business Central does offer some tools that might come in handy in your situation. 

Here's a link to an article that describes some features you could consider, [Features for switching company or environment](https://learn.microsoft.com/dynamics365/business-central/ui-organization-switch#features-for-switching-company-or-environment).

Alternatively, because you have so many companies, you might try out [Company Hub](https://learn.microsoft.com/dynamics365/business-central/company-hub) role? That might make it easier for you to switch between companies.

**Comment by pvreugdenhil** [comment]
Hey , nice mail , feature was also in the latest update of bc.  So fine !
Thanks for the response and enjoy the weekend

Op vr 28 okt. 2022 om 13:50 schreef Brent Holtorf ***@***.***>
