### ISSUE TITLE
Non-Inventory items does not work as component in production

### ISSUE THREAD

**Issue by peikba** [MicrosoftDocs/dynamics365smb-docs#91]
Hi Guys,
I just tested the Non-Inventory items in production.
It does not work I'm afraid.
Please see my two blogs:
https://dynamicsuser.net/nav/b/peik/posts/using-infinite-components-in-a-dynamics-365-bc-production
and 
https://dynamicsuser.net/nav/b/peik/posts/using-infinite-components-in-a-dynamics-365-bc-production-part-2-the-withdraw

If you have a hint please let me know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea248ae7-d4ca-5879-0785-d097f3250b5a
* Version Independent ID: adefc344-0777-caa6-7052-416302d9dbb8
* Content: [Understanding Item Types - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-about-item-types)
* Content Source: [business-central/inventory-about-item-types.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-about-item-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hi - I have assigned a bug with your links to the App Sustained Engineering team.

Going forward, please do not use this documentation feedback mechanism for product issues. Instead, report it through your Microsoft support channel.

Soren, Business Centarl writer

**Comment by AndreiPanko** [comment]
@peikba 
Hi Peik,

I looked into the scenario and closed it "By design" and here is why:
There is no correlation between consumed and purchased "Noninventory" item. You may buy some or may never buy any. In both cases this will not affect inventory (or raw materials) account.
That's why when these items are consumed in production we do not post any G/L entry, as it will lead to disbalance on Inventory (or raw material account).
As result the material cost of output items is higher than cost of consumed raw materials therefore we have difference in WIP account.

This is somehow similar to producing of item with "Indirect Cost %" = 50 (then there is additional output transaction that "Debit: Inventory, Credit: General Posting Setup - Overhead Applied Account".)

Here you can see the two sets of transactions (I shuffle them a bit to make it more noticeable, but turnover and balance are the same)

Scenario1: Producing Item with Indirect Cost (50% ~67ddk)from 1 component (balance stays on 7792)

G/L   Account No. | Description | Amount
-- | -- | --
2130 - RawMaterial | Direct Cost of consumed inventory component | -134
2140 - WIP | Direct Cost of consumed inventory component | 134
2110 - Inventory | Direct Cost of produced product | 134
2140 - WIP | Direct Cost of produced product | -134
2110 - Inventory | Indirect Cost of produced product | 67
7792 - IndirectOverhead | **Indirect   Cost of produced product  (balance on 7792)** | -67

Scenario2: Producing Item without indirect cost from Inventory Component + Non Inv Component (cost 67dkk). Balance stays on 2140.

G/L   Account No. | Description | Amount
-- | -- | --
2130 - RawMaterial | Direct Cost of consumed inventory component | -134
2140 - WIP | Direct Cost of consumed inventory component | 134
2110 - Inventory | Direct Cost of produced product | 134
2140 - WIP | Direct Cost of produced product | -134
2110 - Inventory | Direct Cost of produced product (from NonInv) | 67
2140 - WIP | **Direct   Cost of produced product (from NonInv) (balance on 2140)** | -67

If you have better ideas, I would be happy to hear your suggestion. Feel free to send me a e-mail to andreipa@m********.com

PS
Notice that we can say it is also similar to resources consumption in assembly order

G/L Account No. | Description | Amount
-- | -- | --
2130 - RawMaterial | Direct Cost of consumed inventory component | -134
7270 - InvAdj-Raw | Direct Cost of consumed inventory component | 134
2110 - Inventory | Direct Cost of produced product | 201
7170 - InvAdj-Inv | Direct Cost of produced product | -201
7170 - InvAdj-Inv | Resource cost | 67
7791 - Direct Cost  Applied | **Resource cost (balance on 7791)** | -67
