### ISSUE TITLE
Office 365 License with Business Central

### ISSUE THREAD

**Issue by PaddyPOwer123** [MicrosoftDocs/dynamics365smb-docs#95]
You state in the FAQ you DO NOT NEED an office 365 license for Business Central. Well how do you deploy or use the admin center without an office 365 license?

**Comment by edupont04** [comment]
Hi PaddyPower123, 
We'll post an update to the FAQ, but the guidance is generally this:
- Sign up for a trial using any email account that is not a consumer account such as Hotmail or Gmail.
-  If the account you sign up with is an Office 365 work account (such as joe@mysolution.com) but you have previously associated your domain (mysolution.com) with an Office 365 subscription, then all is still well, and you already have access to the Office 365 administation center and Azure admin center
- If the work account that you sign up with is not an Office 365 account, and you have not associated it with an Office 365 subscription, then we quietly provision a new Azure Active Directory tenant for you so that you have access to the Azure admin center (and the Office 365 admin center)

I hope this answers your question. Otherwise, please let us know.
